yes | sudo apt install acl
yes | sudo apt install acpi
yes | sudo apt install acpi-support-base
yes | sudo apt install acpid
yes | sudo apt install adduser
yes | sudo apt install adwaita-icon-theme
yes | sudo apt install alsa-base
yes | sudo apt install alsa-utils
yes | sudo apt install anacron
yes | sudo apt install apt
yes | sudo apt install apt-file
yes | sudo apt install apt-listchanges
yes | sudo apt install apt-utils
yes | sudo apt install aptitude
yes | sudo apt install aptitude-common
yes | sudo apt install aptitude-doc-en
yes | sudo apt install arc
yes | sudo apt install aspell
yes | sudo apt install aspell-en
yes | sudo apt install at
yes | sudo apt install at-spi2-core
yes | sudo apt install atril
yes | sudo apt install atril-common
yes | sudo apt install autoconf
yes | sudo apt install automake
yes | sudo apt install autotools-dev
yes | sudo apt install avahi-daemon
yes | sudo apt install base-files
yes | sudo apt install base-passwd
yes | sudo apt install bash
yes | sudo apt install bash-completion
yes | sudo apt install bc
yes | sudo apt install bind9-host
yes | sudo apt install binfmt-support
yes | sudo apt install binutils
yes | sudo apt install bleachbit
yes | sudo apt install bsd-mailx
yes | sudo apt install bsdmainutils
yes | sudo apt install bsdutils
yes | sudo apt install build-essential
yes | sudo apt install busybox
yes | sudo apt install bzip2
yes | sudo apt install ca-certificates
yes | sudo apt install ca-certificates-java
yes | sudo apt install caja
yes | sudo apt install caja-common
yes | sudo apt install cmake
yes | sudo apt install cmake-data
yes | sudo apt install coinor-libcbc3
yes | sudo apt install coinor-libcgl1
yes | sudo apt install coinor-libclp1
yes | sudo apt install coinor-libcoinmp1
yes | sudo apt install coinor-libcoinutils3
yes | sudo apt install coinor-libosi1
yes | sudo apt install colord
yes | sudo apt install colord-data
yes | sudo apt install console-setup
yes | sudo apt install console-setup-linux
yes | sudo apt install coreutils
yes | sudo apt install cpio
yes | sudo apt install cpp
yes | sudo apt install cpp-4.8
yes | sudo apt install cpp-4.9
yes | sudo apt install cpufrequtils
yes | sudo apt install crda
yes | sudo apt install cron
yes | sudo apt install cryptsetup-bin
yes | sudo apt install cups
yes | sudo apt install cups-browsed
yes | sudo apt install cups-bsd
yes | sudo apt install cups-client
yes | sudo apt install cups-common
yes | sudo apt install cups-core-drivers
yes | sudo apt install cups-daemon
yes | sudo apt install cups-filters
yes | sudo apt install cups-filters-core-drivers
yes | sudo apt install cups-ppdc
yes | sudo apt install cups-server-common
yes | sudo apt install curl
yes | sudo apt install dash
yes | sudo apt install dbus
yes | sudo apt install dbus-x11
yes | sudo apt install dc
yes | sudo apt install dconf-gsettings-backend
yes | sudo apt install dconf-service
yes | sudo apt install debconf
yes | sudo apt install debconf-i18n
yes | sudo apt install debian-archive-keyring
yes | sudo apt install debian-faq
yes | sudo apt install debianutils
yes | sudo apt install default-jre
yes | sudo apt install default-jre-headless
yes | sudo apt install desktop-base
yes | sudo apt install desktop-file-utils
yes | sudo apt install dh-python
yes | sudo apt install dialog
yes | sudo apt install dictionaries-common
yes | sudo apt install diffutils
yes | sudo apt install discover
yes | sudo apt install discover-data
yes | sudo apt install dmidecode
yes | sudo apt install dmsetup
yes | sudo apt install dmz-cursor-theme
yes | sudo apt install dns-root-data
yes | sudo apt install dnsmasq-base
yes | sudo apt install dnsutils
yes | sudo apt install doc-debian
yes | sudo apt install docbook-xml
yes | sudo apt install docbook-xsl
yes | sudo apt install docutils-common
yes | sudo apt install docutils-doc
yes | sudo apt install dosfstools
yes | sudo apt install doxygen
yes | sudo apt install doxygen-gui
yes | sudo apt install dpkg
yes | sudo apt install dpkg-dev
yes | sudo apt install e2fslibs
yes | sudo apt install e2fsprogs
yes | sudo apt install eclipse-platform
yes | sudo apt install eject
yes | sudo apt install emacsen-common
yes | sudo apt install enchant
yes | sudo apt install engrampa
yes | sudo apt install engrampa-common
yes | sudo apt install eom
yes | sudo apt install eom-common
yes | sudo apt install espeak-data
yes | sudo apt install exim4
yes | sudo apt install exim4-base
yes | sudo apt install exim4-config
yes | sudo apt install exim4-daemon-light
yes | sudo apt install extundelete
yes | sudo apt install fakeroot
yes | sudo apt install ffmpegthumbnailer
yes | sudo apt install file
yes | sudo apt install filezilla
yes | sudo apt install findutils
yes | sudo apt install firebird2.5-common
yes | sudo apt install firebird2.5-server-common
yes | sudo apt install firefox-esr
yes | sudo apt install firmware-linux-free
yes | sudo apt install fontconfig
yes | sudo apt install fontconfig-config
yes | sudo apt install fonts-dejavu
yes | sudo apt install fonts-dejavu-core
yes | sudo apt install fonts-dejavu-extra
yes | sudo apt install fonts-droid
yes | sudo apt install fonts-freefont-ttf
yes | sudo apt install fonts-liberation
yes | sudo apt install fonts-sil-gentium
yes | sudo apt install fonts-sil-gentium-basic
yes | sudo apt install foomatic-db-compressed-ppds
yes | sudo apt install foomatic-db-engine
yes | sudo apt install ftp
yes | sudo apt install fuse
yes | sudo apt install g++
yes | sudo apt install g++-4.9
yes | sudo apt install galculator
yes | sudo apt install gawk
yes | sudo apt install gcc
yes | sudo apt install gcc-4.8
yes | sudo apt install gcc-4.8-base
yes | sudo apt install gcc-4.9
yes | sudo apt install gcc-4.9-base
yes | sudo apt install gconf-service
yes | sudo apt install gconf2
yes | sudo apt install gconf2-common
yes | sudo apt install gcr
yes | sudo apt install gdb
yes | sudo apt install gdbserver
yes | sudo apt install gdisk
yes | sudo apt install geoclue-2.0
yes | sudo apt install geoip-database
yes | sudo apt install gettext-base
yes | sudo apt install ghostscript
yes | sudo apt install gimp
yes | sudo apt install gimp-data
yes | sudo apt install gir1.2-atk-1.0
yes | sudo apt install gir1.2-atspi-2.0
yes | sudo apt install gir1.2-freedesktop
yes | sudo apt install gir1.2-gdkpixbuf-2.0
yes | sudo apt install gir1.2-glib-2.0
yes | sudo apt install gir1.2-gtk-2.0
yes | sudo apt install gir1.2-gtk-3.0
yes | sudo apt install gir1.2-mate-panel
yes | sudo apt install gir1.2-pango-1.0
yes | sudo apt install gir1.2-wnck-3.0
yes | sudo apt install git
yes | sudo apt install git-man
yes | sudo apt install glib-networking
yes | sudo apt install glib-networking-common
yes | sudo apt install glib-networking-services
yes | sudo apt install gnome-accessibility-themes
yes | sudo apt install gnome-icon-theme
yes | sudo apt install gnome-icon-theme-symbolic
yes | sudo apt install gnome-keyring
yes | sudo apt install gnome-mime-data
yes | sudo apt install gnome-orca
yes | sudo apt install gnome-themes-standard
yes | sudo apt install gnome-themes-standard-data
yes | sudo apt install gnupg
yes | sudo apt install gnupg-agent
yes | sudo apt install gnupg2
yes | sudo apt install gnustep-base-common
yes | sudo apt install gnustep-base-runtime
yes | sudo apt install gnustep-common
yes | sudo apt install gparted
yes | sudo apt install gpgv
yes | sudo apt install grep
yes | sudo apt install groff-base
yes | sudo apt install grub-common
yes | sudo apt install grub-pc
yes | sudo apt install grub-pc-bin
yes | sudo apt install grub2-common
yes | sudo apt install gsettings-desktop-schemas
yes | sudo apt install gsfonts
yes | sudo apt install gsfonts-x11
yes | sudo apt install gstreamer0.10-alsa
yes | sudo apt install gstreamer0.10-gconf
yes | sudo apt install gstreamer0.10-plugins-base
yes | sudo apt install gstreamer0.10-plugins-good
yes | sudo apt install gstreamer0.10-x
yes | sudo apt install gstreamer1.0-libav
yes | sudo apt install gstreamer1.0-plugins-base
yes | sudo apt install gstreamer1.0-plugins-good
yes | sudo apt install gstreamer1.0-x
yes | sudo apt install gtk2-engines
yes | sudo apt install gtk2-engines-murrine
yes | sudo apt install gtk2-engines-pixbuf
yes | sudo apt install gvfs
yes | sudo apt install gvfs-backends
yes | sudo apt install gvfs-bin
yes | sudo apt install gvfs-common
yes | sudo apt install gvfs-daemons
yes | sudo apt install gvfs-libs
yes | sudo apt install gzip
yes | sudo apt install hdparm
yes | sudo apt install hicolor-icon-theme
yes | sudo apt install host
yes | sudo apt install hostname
yes | sudo apt install hp-ppd
yes | sudo apt install hplip
yes | sudo apt install hplip-data
yes | sudo apt install htop
yes | sudo apt install hunspell-en-us
yes | sudo apt install hyphen-en-us
yes | sudo apt install i965-va-driver
yes | sudo apt install iamerican
yes | sudo apt install ibritish
yes | sudo apt install iceweasel
yes | sudo apt install ienglish-common
yes | sudo apt install ifupdown
yes | sudo apt install info
yes | sudo apt install init
yes | sudo apt install init-system-helpers
yes | sudo apt install initramfs-tools
yes | sudo apt install initscripts
yes | sudo apt install insserv
yes | sudo apt install install-info
yes | sudo apt install installation-report
yes | sudo apt install iproute2
yes | sudo apt install iptables
yes | sudo apt install iputils-arping
yes | sudo apt install iputils-ping
yes | sudo apt install ipxe-qemu
yes | sudo apt install irqbalance
yes | sudo apt install isc-dhcp-client
yes | sudo apt install isc-dhcp-common
yes | sudo apt install iso-codes
yes | sudo apt install ispell
yes | sudo apt install iw
yes | sudo apt install java-common
yes | sudo apt install javascript-common
yes | sudo apt install kate-data
yes | sudo apt install katepart
yes | sudo apt install kbd
yes | sudo apt install kde-runtime
yes | sudo apt install kde-runtime-data
yes | sudo apt install kdelibs-bin
yes | sudo apt install kdelibs5-data
yes | sudo apt install kdelibs5-plugins
yes | sudo apt install kdoctools
yes | sudo apt install keyboard-configuration
yes | sudo apt install klibc-utils
yes | sudo apt install kmod
yes | sudo apt install konsole
yes | sudo apt install krb5-locales
yes | sudo apt install laptop-detect
yes | sudo apt install leafpad
yes | sudo apt install less
yes | sudo apt install liba52-0.7.4
yes | sudo apt install libaa1
yes | sudo apt install libaacs0
yes | sudo apt install libabw-0.1-1
yes | sudo apt install libacl1
yes | sudo apt install libaio1
yes | sudo apt install libalgorithm-c3-perl
yes | sudo apt install libalgorithm-diff-perl
yes | sudo apt install libalgorithm-diff-xs-perl
yes | sudo apt install libalgorithm-merge-perl
yes | sudo apt install libamd2.3.1
yes | sudo apt install libao-common
yes | sudo apt install libao4
yes | sudo apt install libapt-inst1.5
yes | sudo apt install libapt-pkg-perl
yes | sudo apt install libapt-pkg4.12
yes | sudo apt install libarchive-extract-perl
yes | sudo apt install libarchive13
yes | sudo apt install libart-2.0-2
yes | sudo apt install libasan0
yes | sudo apt install libasan1
yes | sudo apt install libasound2
yes | sudo apt install libasound2-data
yes | sudo apt install libasound2-plugins
yes | sudo apt install libaspell15
yes | sudo apt install libasprintf0c2
yes | sudo apt install libass5
yes | sudo apt install libassuan0
yes | sudo apt install libasyncns0
yes | sudo apt install libatasmart4
yes | sudo apt install libatk-adaptor
yes | sudo apt install libatk-bridge2.0-0
yes | sudo apt install libatk-wrapper-java
yes | sudo apt install libatk-wrapper-java-jni
yes | sudo apt install libatk1.0-0
yes | sudo apt install libatk1.0-data
yes | sudo apt install libatkmm-1.6-1
yes | sudo apt install libatomic1
yes | sudo apt install libatrildocument3
yes | sudo apt install libatrilview3
yes | sudo apt install libatspi2.0-0
yes | sudo apt install libattica0.4
yes | sudo apt install libattr1
yes | sudo apt install libaudio2
yes | sudo apt install libaudit-common
yes | sudo apt install libaudit1
yes | sudo apt install libauthen-sasl-perl
yes | sudo apt install libavahi-client3
yes | sudo apt install libavahi-common-data
yes | sudo apt install libavahi-common3
yes | sudo apt install libavahi-core7
yes | sudo apt install libavahi-glib1
yes | sudo apt install libavc1394-0
yes | sudo apt install libavcodec56
yes | sudo apt install libavformat56
yes | sudo apt install libavresample2
yes | sudo apt install libavutil54
yes | sudo apt install libbabl-0.1-0
yes | sudo apt install libbasicusageenvironment0
yes | sudo apt install libbind9-90
yes | sudo apt install libblas-common
yes | sudo apt install libblas3
yes | sudo apt install libblkid1
yes | sudo apt install libbluetooth3
yes | sudo apt install libbluray1
yes | sudo apt install libbonobo2-0
yes | sudo apt install libbonobo2-common
yes | sudo apt install libbonoboui2-0
yes | sudo apt install libbonoboui2-common
yes | sudo apt install libboost-date-time1.55.0
yes | sudo apt install libboost-iostreams1.55.0
yes | sudo apt install libboost-system1.55.0
yes | sudo apt install libboost-thread1.55.0
yes | sudo apt install libbrlapi0.6
yes | sudo apt install libbsd0
yes | sudo apt install libbz2-1.0
yes | sudo apt install libc-bin
yes | sudo apt install libc-dev-bin
yes | sudo apt install libc6
yes | sudo apt install libc6-dbg
yes | sudo apt install libc6-dev
yes | sudo apt install libc6-i686
yes | sudo apt install libcaca0
yes | sudo apt install libcairo-gobject2
yes | sudo apt install libcairo-perl
yes | sudo apt install libcairo2
yes | sudo apt install libcairomm-1.0-1
yes | sudo apt install libcaja-extension1
yes | sudo apt install libcamd2.3.1
yes | sudo apt install libcanberra-gtk-module
yes | sudo apt install libcanberra-gtk0
yes | sudo apt install libcanberra-gtk3-0
yes | sudo apt install libcanberra-gtk3-module
yes | sudo apt install libcanberra0
yes | sudo apt install libcap-ng0
yes | sudo apt install libcap2
yes | sudo apt install libcap2-bin
yes | sudo apt install libccolamd2.8.0
yes | sudo apt install libcddb2
yes | sudo apt install libcdio-cdda1
yes | sudo apt install libcdio-paranoia1
yes | sudo apt install libcdio13
yes | sudo apt install libcdparanoia0
yes | sudo apt install libcdr-0.1-1
yes | sudo apt install libcgi-fast-perl
yes | sudo apt install libcgi-pm-perl
yes | sudo apt install libcholmod2.1.2
yes | sudo apt install libchromaprint0
yes | sudo apt install libcilkrts5
yes | sudo apt install libclang1-3.5
yes | sudo apt install libclass-accessor-perl
yes | sudo apt install libclass-c3-perl
yes | sudo apt install libclass-c3-xs-perl
yes | sudo apt install libclass-isa-perl
yes | sudo apt install libcloog-isl4
yes | sudo apt install libclucene-contribs1
yes | sudo apt install libclucene-core1
yes | sudo apt install libcmis-0.4-4
yes | sudo apt install libcolamd2.8.0
yes | sudo apt install libcolord2
yes | sudo apt install libcolorhug2
yes | sudo apt install libcomerr2
yes | sudo apt install libconfig-file-perl
yes | sudo apt install libcpan-meta-perl
yes | sudo apt install libcpufreq0
yes | sudo apt install libcroco3
yes | sudo apt install libcryptsetup4
yes | sudo apt install libcrystalhd3
yes | sudo apt install libcups2
yes | sudo apt install libcupscgi1
yes | sudo apt install libcupsfilters1
yes | sudo apt install libcupsimage2
yes | sudo apt install libcupsmime1
yes | sudo apt install libcupsppdc1
yes | sudo apt install libcurl3
yes | sudo apt install libcurl3-gnutls
yes | sudo apt install libcwidget3
yes | sudo apt install libdaemon0
yes | sudo apt install libdata-optlist-perl
yes | sudo apt install libdata-section-perl
yes | sudo apt install libdatrie1
yes | sudo apt install libdb5.3
yes | sudo apt install libdb5.3-java
yes | sudo apt install libdb5.3-java-jni
yes | sudo apt install libdbus-1-3
yes | sudo apt install libdbus-glib-1-2
yes | sudo apt install libdbusmenu-qt2
yes | sudo apt install libdc1394-22
yes | sudo apt install libdca0
yes | sudo apt install libdconf1
yes | sudo apt install libdebconfclient0
yes | sudo apt install libdevmapper-event1.02.1
yes | sudo apt install libdevmapper1.02.1
yes | sudo apt install libdirectfb-1.2-9
yes | sudo apt install libdiscover2
yes | sudo apt install libdjvulibre-text
yes | sudo apt install libdjvulibre21
yes | sudo apt install libdlrestrictions1
yes | sudo apt install libdns-export100
yes | sudo apt install libdns100
yes | sudo apt install libdotconf0
yes | sudo apt install libdpkg-perl
yes | sudo apt install libdrm-dev
yes | sudo apt install libdrm-intel1
yes | sudo apt install libdrm-nouveau2
yes | sudo apt install libdrm-radeon1
yes | sudo apt install libdrm2
yes | sudo apt install libdv4
yes | sudo apt install libdvbpsi9
yes | sudo apt install libdvdnav4
yes | sudo apt install libdvdread4
yes | sudo apt install libe-book-0.1-1
yes | sudo apt install libebml4
yes | sudo apt install libedit2
yes | sudo apt install libegl1-mesa
yes | sudo apt install libegl1-mesa-drivers
yes | sudo apt install libelf1
yes | sudo apt install libelfg0
yes | sudo apt install libenca0
yes | sudo apt install libenchant1c2a
yes | sudo apt install libencode-locale-perl
yes | sudo apt install libeot0
yes | sudo apt install libepoxy0
yes | sudo apt install libept1.4.12
yes | sudo apt install liberror-perl
yes | sudo apt install libespeak1
yes | sudo apt install libestr0
yes | sudo apt install libetonyek-0.1-1
yes | sudo apt install libevdev2
yes | sudo apt install libevent-2.0-5
yes | sudo apt install libexempi3
yes | sudo apt install libexif12
yes | sudo apt install libexiv2-13
yes | sudo apt install libexpat1
yes | sudo apt install libexpat1-dev
yes | sudo apt install libexttextcat-2.0-0
yes | sudo apt install libfaad2
yes | sudo apt install libfakeroot
yes | sudo apt install libfam0
yes | sudo apt install libfbclient2
yes | sudo apt install libfbembed2.5
yes | sudo apt install libfcgi-perl
yes | sudo apt install libfdt1
yes | sudo apt install libffi6
yes | sudo apt install libffmpegthumbnailer4
yes | sudo apt install libfftw3-single3
yes | sudo apt install libfile-basedir-perl
yes | sudo apt install libfile-copy-recursive-perl
yes | sudo apt install libfile-desktopentry-perl
yes | sudo apt install libfile-fcntllock-perl
yes | sudo apt install libfile-listing-perl
yes | sudo apt install libfile-mimeinfo-perl
yes | sudo apt install libflac8
yes | sudo apt install libflite1
yes | sudo apt install libfont-afm-perl
yes | sudo apt install libfontconfig1
yes | sudo apt install libfontembed1
yes | sudo apt install libfontenc1
yes | sudo apt install libfreehand-0.1-1
yes | sudo apt install libfreerdp-cache1.1
yes | sudo apt install libfreerdp-client1.1
yes | sudo apt install libfreerdp-codec1.1
yes | sudo apt install libfreerdp-common1.1.0
yes | sudo apt install libfreerdp-core1.1
yes | sudo apt install libfreerdp-crypto1.1
yes | sudo apt install libfreerdp-gdi1.1
yes | sudo apt install libfreerdp-locale1.1
yes | sudo apt install libfreerdp-primitives1.1
yes | sudo apt install libfreerdp-rail1.1
yes | sudo apt install libfreerdp-utils1.1
yes | sudo apt install libfreetype6
yes | sudo apt install libfribidi0
yes | sudo apt install libfuse2
yes | sudo apt install libgail-common
yes | sudo apt install libgail18
yes | sudo apt install libgbm1
yes | sudo apt install libgc1c2
yes | sudo apt install libgcc-4.8-dev
yes | sudo apt install libgcc-4.9-dev
yes | sudo apt install libgcc1
yes | sudo apt install libgck-1-0
yes | sudo apt install libgconf-2-4
yes | sudo apt install libgconf2-4
yes | sudo apt install libgcr-3-common
yes | sudo apt install libgcr-base-3-1
yes | sudo apt install libgcr-ui-3-1
yes | sudo apt install libgcrypt20
yes | sudo apt install libgd3
yes | sudo apt install libgdbm3
yes | sudo apt install libgdk-pixbuf2.0-0
yes | sudo apt install libgdk-pixbuf2.0-common
yes | sudo apt install libgegl-0.2-0
yes | sudo apt install libgeoip1
yes | sudo apt install libgfortran3
yes | sudo apt install libgif4
yes | sudo apt install libgimp2.0
yes | sudo apt install libgirepository-1.0-1
yes | sudo apt install libgksu2-0
yes | sudo apt install libgl1-mesa-dev
yes | sudo apt install libgl1-mesa-dri
yes | sudo apt install libgl1-mesa-glx
yes | sudo apt install libglade2-0
yes | sudo apt install libglapi-mesa
yes | sudo apt install libgles1-mesa
yes | sudo apt install libgles2-mesa
yes | sudo apt install libglew1.10
yes | sudo apt install libglib-perl
yes | sudo apt install libglib2.0-0
yes | sudo apt install libglib2.0-bin
yes | sudo apt install libglib2.0-data
yes | sudo apt install libglibmm-2.4-1c2a
yes | sudo apt install libgltf-0.0-0
yes | sudo apt install libglu1-mesa
yes | sudo apt install libglu1-mesa-dev
yes | sudo apt install libgmp10
yes | sudo apt install libgnome-2-0
yes | sudo apt install libgnome-keyring-common
yes | sudo apt install libgnome-keyring0
yes | sudo apt install libgnome2-0
yes | sudo apt install libgnome2-bin
yes | sudo apt install libgnome2-common
yes | sudo apt install libgnomecanvas2-0
yes | sudo apt install libgnomecanvas2-common
yes | sudo apt install libgnomeui-0
yes | sudo apt install libgnomeui-common
yes | sudo apt install libgnomevfs2-0
yes | sudo apt install libgnomevfs2-common
yes | sudo apt install libgnomevfs2-extra
yes | sudo apt install libgnustep-base1.24
yes | sudo apt install libgnutls-deb0-28
yes | sudo apt install libgnutls-openssl27
yes | sudo apt install libgoa-1.0-0b
yes | sudo apt install libgoa-1.0-common
yes | sudo apt install libgomp1
yes | sudo apt install libgpg-error0
yes | sudo apt install libgpgme++2
yes | sudo apt install libgpgme11
yes | sudo apt install libgphoto2-6
yes | sudo apt install libgphoto2-l10n
yes | sudo apt install libgphoto2-port10
yes | sudo apt install libgpm2
yes | sudo apt install libgraphite2-3
yes | sudo apt install libgroupsock1
yes | sudo apt install libgs9
yes | sudo apt install libgs9-common
yes | sudo apt install libgsm1
yes | sudo apt install libgssapi-krb5-2
yes | sudo apt install libgstreamer-plugins-base0.10-0
yes | sudo apt install libgstreamer-plugins-base1.0-0
yes | sudo apt install libgstreamer0.10-0
yes | sudo apt install libgstreamer1.0-0
yes | sudo apt install libgtk-3-0
yes | sudo apt install libgtk-3-bin
yes | sudo apt install libgtk-3-common
yes | sudo apt install libgtk2-perl
yes | sudo apt install libgtk2.0-0
yes | sudo apt install libgtk2.0-bin
yes | sudo apt install libgtk2.0-common
yes | sudo apt install libgtkmm-2.4-1c2a
yes | sudo apt install libgtksourceview2.0-0
yes | sudo apt install libgtksourceview2.0-common
yes | sudo apt install libgtop2-7
yes | sudo apt install libgtop2-common
yes | sudo apt install libgudev-1.0-0
yes | sudo apt install libgusb2
yes | sudo apt install libgutenprint2
yes | sudo apt install libgxps2
yes | sudo apt install libharfbuzz-icu0
yes | sudo apt install libharfbuzz0b
yes | sudo apt install libhogweed2
yes | sudo apt install libhpmud0
yes | sudo apt install libhtml-form-perl
yes | sudo apt install libhtml-format-perl
yes | sudo apt install libhtml-parser-perl
yes | sudo apt install libhtml-tagset-perl
yes | sudo apt install libhtml-tree-perl
yes | sudo apt install libhttp-cookies-perl
yes | sudo apt install libhttp-daemon-perl
yes | sudo apt install libhttp-date-perl
yes | sudo apt install libhttp-message-perl
yes | sudo apt install libhttp-negotiate-perl
yes | sudo apt install libhunspell-1.3-0
yes | sudo apt install libhyphen0
yes | sudo apt install libice6
yes | sudo apt install libicu52
yes | sudo apt install libidn11
yes | sudo apt install libiec61883-0
yes | sudo apt install libieee1284-3
yes | sudo apt install libijs-0.35
yes | sudo apt install libilmbase6
yes | sudo apt install libimobiledevice4
yes | sudo apt install libintl-perl
yes | sudo apt install libio-html-perl
yes | sudo apt install libio-socket-ip-perl
yes | sudo apt install libio-socket-ssl-perl
yes | sudo apt install libio-string-perl
yes | sudo apt install libiodbc2
yes | sudo apt install libirs-export91
yes | sudo apt install libisc-export95
yes | sudo apt install libisc95
yes | sudo apt install libisccc90
yes | sudo apt install libisccfg-export90
yes | sudo apt install libisccfg90
yes | sudo apt install libiscsi2
yes | sudo apt install libisl10
yes | sudo apt install libiso9660-8
yes | sudo apt install libitm1
yes | sudo apt install libjack-jackd2-0
yes | sudo apt install libjasper1
yes | sudo apt install libjavascriptcoregtk-3.0-0
yes | sudo apt install libjbig0
yes | sudo apt install libjbig2dec0
yes | sudo apt install libjim0.75
yes | sudo apt install libjpeg62-turbo
yes | sudo apt install libjs-excanvas
yes | sudo apt install libjs-jquery
yes | sudo apt install libjs-underscore
yes | sudo apt install libjson-c2
yes | sudo apt install libjson-glib-1.0-0
yes | sudo apt install libjson-glib-1.0-common
yes | sudo apt install libk5crypto3
yes | sudo apt install libkactivities-bin
yes | sudo apt install libkactivities-models1
yes | sudo apt install libkactivities6
yes | sudo apt install libkate1
yes | sudo apt install libkatepartinterfaces4
yes | sudo apt install libkcmutils4
yes | sudo apt install libkde3support4
yes | sudo apt install libkdeclarative5
yes | sudo apt install libkdecore5
yes | sudo apt install libkdesu5
yes | sudo apt install libkdeui5
yes | sudo apt install libkdewebkit5
yes | sudo apt install libkdnssd4
yes | sudo apt install libkemoticons4
yes | sudo apt install libkeyutils1
yes | sudo apt install libkfile4
yes | sudo apt install libkhtml5
yes | sudo apt install libkio5
yes | sudo apt install libkjsapi4
yes | sudo apt install libkjsembed4
yes | sudo apt install libklibc
yes | sudo apt install libkmediaplayer4
yes | sudo apt install libkmod2
yes | sudo apt install libknewstuff3-4
yes | sudo apt install libknotifyconfig4
yes | sudo apt install libkntlm4
yes | sudo apt install libkonq-common
yes | sudo apt install libkonq5-templates
yes | sudo apt install libkonq5abi1
yes | sudo apt install libkparts4
yes | sudo apt install libkpathsea6
yes | sudo apt install libkpty4
yes | sudo apt install libkrb5-3
yes | sudo apt install libkrb5support0
yes | sudo apt install libkrosscore4
yes | sudo apt install libksba8
yes | sudo apt install libktexteditor4
yes | sudo apt install libkxmlrpcclient4
yes | sudo apt install liblangtag1
yes | sudo apt install liblapack3
yes | sudo apt install liblcms2-2
yes | sudo apt install liblcms2-utils
yes | sudo apt install libldap-2.4-2
yes | sudo apt install libldb1
yes | sudo apt install liblightdm-gobject-1-0
yes | sudo apt install liblircclient0
yes | sudo apt install liblist-moreutils-perl
yes | sudo apt install liblivemedia23
yes | sudo apt install libllvm3.5
yes | sudo apt install liblocale-gettext-perl
yes | sudo apt install liblockfile-bin
yes | sudo apt install liblockfile1
yes | sudo apt install liblog-message-perl
yes | sudo apt install liblog-message-simple-perl
yes | sudo apt install liblogging-stdlog0
yes | sudo apt install liblognorm1
yes | sudo apt install liblouis-data
yes | sudo apt install liblouis2
yes | sudo apt install libltdl-dev
yes | sudo apt install libltdl7
yes | sudo apt install liblua5.2-0
yes | sudo apt install liblvm2app2.2
yes | sudo apt install liblwp-mediatypes-perl
yes | sudo apt install liblwp-protocol-https-perl
yes | sudo apt install liblwres90
yes | sudo apt install liblzma5
yes | sudo apt install liblzo2-2
yes | sudo apt install libmad0
yes | sudo apt install libmagic1
yes | sudo apt install libmailtools-perl
yes | sudo apt install libmarco-private0
yes | sudo apt install libmate-desktop-2-17
yes | sudo apt install libmate-menu2
yes | sudo apt install libmate-panel-applet-4-1
yes | sudo apt install libmate-slab0
yes | sudo apt install libmate-window-settings1
yes | sudo apt install libmatedict6
yes | sudo apt install libmatekbd-common
yes | sudo apt install libmatekbd4
yes | sudo apt install libmateweather-common
yes | sudo apt install libmateweather1
yes | sudo apt install libmatroska6
yes | sudo apt install libmbim-glib4
yes | sudo apt install libmbim-proxy
yes | sudo apt install libmhash2
yes | sudo apt install libmm-glib0
yes | sudo apt install libmng1
yes | sudo apt install libmnl0
yes | sudo apt install libmodplug1
yes | sudo apt install libmodule-build-perl
yes | sudo apt install libmodule-pluggable-perl
yes | sudo apt install libmodule-signature-perl
yes | sudo apt install libmount1
yes | sudo apt install libmp3lame0
yes | sudo apt install libmpc3
yes | sudo apt install libmpcdec6
yes | sudo apt install libmpdec2
yes | sudo apt install libmpeg2-4
yes | sudo apt install libmpfr4
yes | sudo apt install libmro-compat-perl
yes | sudo apt install libmspub-0.1-1
yes | sudo apt install libmtdev1
yes | sudo apt install libmtp-common
yes | sudo apt install libmtp-runtime
yes | sudo apt install libmtp9
yes | sudo apt install libmwaw-0.3-3
yes | sudo apt install libmysqlclient18
yes | sudo apt install libmythes-1.2-0
yes | sudo apt install libncurses5
yes | sudo apt install libncursesw5
yes | sudo apt install libndp0
yes | sudo apt install libneon27-gnutls
yes | sudo apt install libnepomuk4
yes | sudo apt install libnepomukcore4
yes | sudo apt install libnepomukquery4a
yes | sudo apt install libnepomukutils4
yes | sudo apt install libnet-dbus-perl
yes | sudo apt install libnet-http-perl
yes | sudo apt install libnet-smtp-ssl-perl
yes | sudo apt install libnet-ssleay-perl
yes | sudo apt install libnetfilter-acct1
yes | sudo apt install libnetfilter-conntrack3
yes | sudo apt install libnettle4
yes | sudo apt install libnewt0.52
yes | sudo apt install libnfnetlink0
yes | sudo apt install libnfsidmap2
yes | sudo apt install libnl-3-200
yes | sudo apt install libnl-genl-3-200
yes | sudo apt install libnl-route-3-200
yes | sudo apt install libnm-glib-vpn1
yes | sudo apt install libnm-glib4
yes | sudo apt install libnm-gtk-common
yes | sudo apt install libnm-gtk0
yes | sudo apt install libnm-util2
yes | sudo apt install libnotify4
yes | sudo apt install libnspr4
yes | sudo apt install libnss-mdns
yes | sudo apt install libnss3
yes | sudo apt install libntdb1
yes | sudo apt install libntrack-qt4-1
yes | sudo apt install libntrack0
yes | sudo apt install libnuma1
yes | sudo apt install libobjc-4.9-dev
yes | sudo apt install libobjc4
yes | sudo apt install libodfgen-0.1-1
yes | sudo apt install libogg0
yes | sudo apt install libopenexr6
yes | sudo apt install libopenjpeg5
yes | sudo apt install libopenraw1
yes | sudo apt install libopenvg1-mesa
yes | sudo apt install libopus0
yes | sudo apt install liborbit-2-0
yes | sudo apt install liborc-0.4-0
yes | sudo apt install liborcus-0.8-0
yes | sudo apt install libp11-kit0
yes | sudo apt install libpackage-constants-perl
yes | sudo apt install libpam-gnome-keyring
yes | sudo apt install libpam-modules
yes | sudo apt install libpam-modules-bin
yes | sudo apt install libpam-runtime
yes | sudo apt install libpam-systemd
yes | sudo apt install libpam0g
yes | sudo apt install libpango-1.0-0
yes | sudo apt install libpango-perl
yes | sudo apt install libpango1.0-0
yes | sudo apt install libpangocairo-1.0-0
yes | sudo apt install libpangoft2-1.0-0
yes | sudo apt install libpangomm-1.4-1
yes | sudo apt install libpangox-1.0-0
yes | sudo apt install libpangoxft-1.0-0
yes | sudo apt install libpaper-utils
yes | sudo apt install libpaper1
yes | sudo apt install libparams-util-perl
yes | sudo apt install libparse-debianchangelog-perl
yes | sudo apt install libparted-fs-resize0
yes | sudo apt install libparted2
yes | sudo apt install libpcap0.8
yes | sudo apt install libpci3
yes | sudo apt install libpciaccess0
yes | sudo apt install libpcre3
yes | sudo apt install libpcsclite1
yes | sudo apt install libperl4-corelibs-perl
yes | sudo apt install libperl5.20
yes | sudo apt install libphonon4
yes | sudo apt install libpipeline1
yes | sudo apt install libpixman-1-0
yes | sudo apt install libplasma3
yes | sudo apt install libplist2
yes | sudo apt install libpng12-0
yes | sudo apt install libpod-latex-perl
yes | sudo apt install libpod-readme-perl
yes | sudo apt install libpolkit-agent-1-0
yes | sudo apt install libpolkit-backend-1-0
yes | sudo apt install libpolkit-gobject-1-0
yes | sudo apt install libpolkit-qt-1-1
yes | sudo apt install libpoppler-glib8
yes | sudo apt install libpoppler46
yes | sudo apt install libpopt0
yes | sudo apt install libportaudio2
yes | sudo apt install libpostproc52
yes | sudo apt install libprocps3
yes | sudo apt install libproxy-tools
yes | sudo apt install libproxy1
yes | sudo apt install libpsl0
yes | sudo apt install libpth20
yes | sudo apt install libpthread-stubs0-dev
yes | sudo apt install libpulse-mainloop-glib0
yes | sudo apt install libpulse0
yes | sudo apt install libpulsedsp
yes | sudo apt install libpython-dev
yes | sudo apt install libpython-stdlib
yes | sudo apt install libpython2.7
yes | sudo apt install libpython2.7-dev
yes | sudo apt install libpython2.7-minimal
yes | sudo apt install libpython2.7-stdlib
yes | sudo apt install libpython3-stdlib
yes | sudo apt install libpython3.4
yes | sudo apt install libpython3.4-minimal
yes | sudo apt install libpython3.4-stdlib
yes | sudo apt install libqca2
yes | sudo apt install libqmi-glib1
yes | sudo apt install libqmi-proxy
yes | sudo apt install libqpdf13
yes | sudo apt install libqscintilla2-11
yes | sudo apt install libqscintilla2-l10n
yes | sudo apt install libqt4-core
yes | sudo apt install libqt4-dbus
yes | sudo apt install libqt4-declarative
yes | sudo apt install libqt4-designer
yes | sudo apt install libqt4-dev
yes | sudo apt install libqt4-dev-bin
yes | sudo apt install libqt4-gui
yes | sudo apt install libqt4-help
yes | sudo apt install libqt4-network
yes | sudo apt install libqt4-opengl
yes | sudo apt install libqt4-opengl-dev
yes | sudo apt install libqt4-qt3support
yes | sudo apt install libqt4-script
yes | sudo apt install libqt4-scripttools
yes | sudo apt install libqt4-sql
yes | sudo apt install libqt4-sql-mysql
yes | sudo apt install libqt4-sql-sqlite
yes | sudo apt install libqt4-svg
yes | sudo apt install libqt4-test
yes | sudo apt install libqt4-xml
yes | sudo apt install libqt4-xmlpatterns
yes | sudo apt install libqtassistantclient4
yes | sudo apt install libqtcore4
yes | sudo apt install libqtdbus4
yes | sudo apt install libqtgui4
yes | sudo apt install libqtwebkit-dev
yes | sudo apt install libqtwebkit4
yes | sudo apt install libquadmath0
yes | sudo apt install librados2
yes | sudo apt install libraptor2-0
yes | sudo apt install librarian0
yes | sudo apt install librasqal3
yes | sudo apt install libraw1394-11
yes | sudo apt install librbd1
yes | sudo apt install librdf0
yes | sudo apt install libreadline-dev
yes | sudo apt install libreadline6
yes | sudo apt install libreadline6-dev
yes | sudo apt install libregexp-assemble-perl
yes | sudo apt install libregexp-common-perl
yes | sudo apt install libreoffice-base
yes | sudo apt install libreoffice-calc
yes | sudo apt install libreoffice-common
yes | sudo apt install libreoffice-core
yes | sudo apt install libreoffice-draw
yes | sudo apt install libreoffice-impress
yes | sudo apt install libreoffice-math
yes | sudo apt install libreoffice-writer
yes | sudo apt install libresid-builder0c2a
yes | sudo apt install librest-0.7-0
yes | sudo apt install librevenge-0.0-0
yes | sudo apt install librsvg2-2
yes | sudo apt install librsvg2-common
yes | sudo apt install librtmp1
yes | sudo apt install libsamplerate0
yes | sudo apt install libsane
yes | sudo apt install libsane-common
yes | sudo apt install libsane-extras
yes | sudo apt install libsane-extras-common
yes | sudo apt install libsane-hpaio
yes | sudo apt install libsasl2-2
yes | sudo apt install libsasl2-modules
yes | sudo apt install libsasl2-modules-db
yes | sudo apt install libschroedinger-1.0-0
yes | sudo apt install libsctp1
yes | sudo apt install libsdl-image1.2
yes | sudo apt install libsdl1.2debian
yes | sudo apt install libseccomp2
yes | sudo apt install libsecret-1-0
yes | sudo apt install libsecret-common
yes | sudo apt install libselinux1
yes | sudo apt install libsemanage-common
yes | sudo apt install libsemanage1
yes | sudo apt install libsensors4
yes | sudo apt install libsepol1
yes | sudo apt install libservlet2.5-java
yes | sudo apt install libsgutils2-2
yes | sudo apt install libshine3
yes | sudo apt install libshout3
yes | sudo apt install libsidplay2
yes | sudo apt install libsigc++-2.0-0c2a
yes | sudo apt install libsigsegv2
yes | sudo apt install libslang2
yes | sudo apt install libsm6
yes | sudo apt install libsmartcols1
yes | sudo apt install libsmbclient
yes | sudo apt install libsndfile1
yes | sudo apt install libsnmp-base
yes | sudo apt install libsnmp30
yes | sudo apt install libsoftware-license-perl
yes | sudo apt install libsolid4
yes | sudo apt install libsonic0
yes | sudo apt install libsoprano4
yes | sudo apt install libsoup-gnome2.4-1
yes | sudo apt install libsoup2.4-1
yes | sudo apt install libspectre1
yes | sudo apt install libspeechd2
yes | sudo apt install libspeex1
yes | sudo apt install libspeexdsp1
yes | sudo apt install libspice-server1
yes | sudo apt install libsqlite3-0
yes | sudo apt install libss2
yes | sudo apt install libssh-gcrypt-4
yes | sudo apt install libssh2-1
yes | sudo apt install libssl1.0.0
yes | sudo apt install libstartup-notification0
yes | sudo apt install libstdc++-4.9-dev
yes | sudo apt install libstdc++6
yes | sudo apt install libstreamanalyzer0
yes | sudo apt install libstreams0
yes | sudo apt install libsub-exporter-perl
yes | sudo apt install libsub-install-perl
yes | sudo apt install libsub-name-perl
yes | sudo apt install libswitch-perl
yes | sudo apt install libswscale3
yes | sudo apt install libsysfs2
yes | sudo apt install libsystemd0
yes | sudo apt install libtag1-vanilla
yes | sudo apt install libtag1c2a
yes | sudo apt install libtalloc2
yes | sudo apt install libtasn1-6
yes | sudo apt install libtcl8.6
yes | sudo apt install libtdb1
yes | sudo apt install libteamdctl0
yes | sudo apt install libterm-ui-perl
yes | sudo apt install libtevent0
yes | sudo apt install libtext-charwidth-perl
yes | sudo apt install libtext-iconv-perl
yes | sudo apt install libtext-soundex-perl
yes | sudo apt install libtext-template-perl
yes | sudo apt install libtext-unidecode-perl
yes | sudo apt install libtext-wrapi18n-perl
yes | sudo apt install libthai-data
yes | sudo apt install libthai0
yes | sudo apt install libtheora0
yes | sudo apt install libthreadweaver4
yes | sudo apt install libtie-ixhash-perl
yes | sudo apt install libtiff5
yes | sudo apt install libtimedate-perl
yes | sudo apt install libtinfo-dev
yes | sudo apt install libtinfo5
yes | sudo apt install libtinyxml2.6.2
yes | sudo apt install libtirpc1
yes | sudo apt install libtk8.6
yes | sudo apt install libtokyocabinet9
yes | sudo apt install libtool
yes | sudo apt install libtool-bin
yes | sudo apt install libtwolame0
yes | sudo apt install libtxc-dxtn-s2tc0
yes | sudo apt install libubsan0
yes | sudo apt install libudev1
yes | sudo apt install libudisks2-0
yes | sudo apt install libumfpack5.6.2
yes | sudo apt install libunique-1.0-0
yes | sudo apt install libupnp6
yes | sudo apt install libupower-glib3
yes | sudo apt install liburi-perl
yes | sudo apt install libusageenvironment1
yes | sudo apt install libusb-0.1-4
yes | sudo apt install libusb-1.0-0
yes | sudo apt install libusbmuxd2
yes | sudo apt install libusbredirparser1
yes | sudo apt install libustr-1.0-1
yes | sudo apt install libutempter0
yes | sudo apt install libuuid-perl
yes | sudo apt install libuuid1
yes | sudo apt install libv4l-0
yes | sudo apt install libv4lconvert0
yes | sudo apt install libva-drm1
yes | sudo apt install libva-x11-1
yes | sudo apt install libva1
yes | sudo apt install libvcdinfo0
yes | sudo apt install libvdeplug2
yes | sudo apt install libvdpau1
yes | sudo apt install libvisio-0.1-1
yes | sudo apt install libvisual-0.4-0
yes | sudo apt install libvisual-0.4-plugins
yes | sudo apt install libvlc5
yes | sudo apt install libvlccore8
yes | sudo apt install libvncclient0
yes | sudo apt install libvorbis0a
yes | sudo apt install libvorbisenc2
yes | sudo apt install libvorbisfile3
yes | sudo apt install libvpx1
yes | sudo apt install libvte-2.90-9
yes | sudo apt install libvte-2.90-common
yes | sudo apt install libvte-common
yes | sudo apt install libvte9
yes | sudo apt install libwavpack1
yes | sudo apt install libwayland-client0
yes | sudo apt install libwayland-cursor0
yes | sudo apt install libwayland-egl1-mesa
yes | sudo apt install libwayland-server0
yes | sudo apt install libwbclient0
yes | sudo apt install libwebkitgtk-3.0-0
yes | sudo apt install libwebkitgtk-3.0-common
yes | sudo apt install libwebp5
yes | sudo apt install libwebpdemux1
yes | sudo apt install libwebpmux1
yes | sudo apt install libwebrtc-audio-processing-0
yes | sudo apt install libwinpr-crt0.1
yes | sudo apt install libwinpr-crypto0.1
yes | sudo apt install libwinpr-dsparse0.1
yes | sudo apt install libwinpr-environment0.1
yes | sudo apt install libwinpr-file0.1
yes | sudo apt install libwinpr-handle0.1
yes | sudo apt install libwinpr-heap0.1
yes | sudo apt install libwinpr-input0.1
yes | sudo apt install libwinpr-interlocked0.1
yes | sudo apt install libwinpr-library0.1
yes | sudo apt install libwinpr-path0.1
yes | sudo apt install libwinpr-pool0.1
yes | sudo apt install libwinpr-registry0.1
yes | sudo apt install libwinpr-rpc0.1
yes | sudo apt install libwinpr-sspi0.1
yes | sudo apt install libwinpr-synch0.1
yes | sudo apt install libwinpr-sysinfo0.1
yes | sudo apt install libwinpr-thread0.1
yes | sudo apt install libwinpr-utils0.1
yes | sudo apt install libwmf0.2-7
yes | sudo apt install libwnck-3-0
yes | sudo apt install libwnck-3-common
yes | sudo apt install libwnck-common
yes | sudo apt install libwnck22
yes | sudo apt install libwpd-0.10-10
yes | sudo apt install libwpg-0.3-3
yes | sudo apt install libwps-0.3-3
yes | sudo apt install libwrap0
yes | sudo apt install libwww-perl
yes | sudo apt install libwww-robotrules-perl
yes | sudo apt install libwxbase3.0-0
yes | sudo apt install libwxgtk3.0-0
yes | sudo apt install libx11-6
yes | sudo apt install libx11-data
yes | sudo apt install libx11-dev
yes | sudo apt install libx11-doc
yes | sudo apt install libx11-protocol-perl
yes | sudo apt install libx11-xcb-dev
yes | sudo apt install libx11-xcb1
yes | sudo apt install libx264-142
yes | sudo apt install libxapian22
yes | sudo apt install libxatracker2
yes | sudo apt install libxau-dev
yes | sudo apt install libxau6
yes | sudo apt install libxaw7
yes | sudo apt install libxcb-composite0
yes | sudo apt install libxcb-dri2-0
yes | sudo apt install libxcb-dri2-0-dev
yes | sudo apt install libxcb-dri3-0
yes | sudo apt install libxcb-dri3-dev
yes | sudo apt install libxcb-glx0
yes | sudo apt install libxcb-glx0-dev
yes | sudo apt install libxcb-keysyms1
yes | sudo apt install libxcb-present-dev
yes | sudo apt install libxcb-present0
yes | sudo apt install libxcb-randr0
yes | sudo apt install libxcb-randr0-dev
yes | sudo apt install libxcb-render0
yes | sudo apt install libxcb-render0-dev
yes | sudo apt install libxcb-shape0
yes | sudo apt install libxcb-shape0-dev
yes | sudo apt install libxcb-shm0
yes | sudo apt install libxcb-sync-dev
yes | sudo apt install libxcb-sync1
yes | sudo apt install libxcb-util0
yes | sudo apt install libxcb-xfixes0
yes | sudo apt install libxcb-xfixes0-dev
yes | sudo apt install libxcb-xv0
yes | sudo apt install libxcb1
yes | sudo apt install libxcb1-dev
yes | sudo apt install libxcomposite1
yes | sudo apt install libxcursor1
yes | sudo apt install libxdamage-dev
yes | sudo apt install libxdamage1
yes | sudo apt install libxdmcp-dev
yes | sudo apt install libxdmcp6
yes | sudo apt install libxen-4.4
yes | sudo apt install libxenstore3.0
yes | sudo apt install libxext-dev
yes | sudo apt install libxext6
yes | sudo apt install libxfixes-dev
yes | sudo apt install libxfixes3
yes | sudo apt install libxfont1
yes | sudo apt install libxft2
yes | sudo apt install libxi6
yes | sudo apt install libxinerama1
yes | sudo apt install libxkbcommon0
yes | sudo apt install libxkbfile1
yes | sudo apt install libxklavier16
yes | sudo apt install libxml-libxml-perl
yes | sudo apt install libxml-namespacesupport-perl
yes | sudo apt install libxml-parser-perl
yes | sudo apt install libxml-sax-base-perl
yes | sudo apt install libxml-sax-expat-perl
yes | sudo apt install libxml-sax-perl
yes | sudo apt install libxml-twig-perl
yes | sudo apt install libxml-xpathengine-perl
yes | sudo apt install libxml2
yes | sudo apt install libxml2-utils
yes | sudo apt install libxmu6
yes | sudo apt install libxmuu1
yes | sudo apt install libxpm4
yes | sudo apt install libxrandr2
yes | sudo apt install libxrender1
yes | sudo apt install libxres1
yes | sudo apt install libxshmfence-dev
yes | sudo apt install libxshmfence1
yes | sudo apt install libxslt1.1
yes | sudo apt install libxss1
yes | sudo apt install libxt6
yes | sudo apt install libxtables10
yes | sudo apt install libxtst6
yes | sudo apt install libxv1
yes | sudo apt install libxvidcore4
yes | sudo apt install libxvmc1
yes | sudo apt install libxxf86dga1
yes | sudo apt install libxxf86vm-dev
yes | sudo apt install libxxf86vm1
yes | sudo apt install libyajl2
yes | sudo apt install libzvbi-common
yes | sudo apt install libzvbi0
yes | sudo apt install lightdm
yes | sudo apt install lightdm-gtk-greeter
yes | sudo apt install linux-base
yes | sudo apt install linux-compiler-gcc-4.8-x86
yes | sudo apt install linux-headers-3.16.0-4-586
yes | sudo apt install linux-headers-3.16.0-4-686-pae
yes | sudo apt install linux-headers-3.16.0-4-common
yes | sudo apt install linux-image-3.16.0-4-586
yes | sudo apt install linux-image-3.16.0-4-686-pae
yes | sudo apt install linux-image-586
yes | sudo apt install linux-kbuild-3.16
yes | sudo apt install linux-libc-dev
yes | sudo apt install lksctp-tools
yes | sudo apt install locales
yes | sudo apt install login
yes | sudo apt install logrotate
yes | sudo apt install lsb-base
yes | sudo apt install lsb-release
yes | sudo apt install lsof
yes | sudo apt install m4
yes | sudo apt install make
yes | sudo apt install man-db
yes | sudo apt install manpages
yes | sudo apt install manpages-dev
yes | sudo apt install marco
yes | sudo apt install marco-common
yes | sudo apt install mate-applets
yes | sudo apt install mate-applets-common
yes | sudo apt install mate-backgrounds
yes | sudo apt install mate-control-center
yes | sudo apt install mate-control-center-common
yes | sudo apt install mate-desktop
yes | sudo apt install mate-desktop-common
yes | sudo apt install mate-desktop-environment
yes | sudo apt install mate-desktop-environment-core
yes | sudo apt install mate-icon-theme
yes | sudo apt install mate-icon-theme-faenza
yes | sudo apt install mate-media
yes | sudo apt install mate-media-common
yes | sudo apt install mate-media-pulse
yes | sudo apt install mate-menus
yes | sudo apt install mate-notification-daemon
yes | sudo apt install mate-panel
yes | sudo apt install mate-panel-common
yes | sudo apt install mate-polkit
yes | sudo apt install mate-polkit-common
yes | sudo apt install mate-power-manager
yes | sudo apt install mate-power-manager-common
yes | sudo apt install mate-screensaver
yes | sudo apt install mate-screensaver-common
yes | sudo apt install mate-session-manager
yes | sudo apt install mate-settings-daemon
yes | sudo apt install mate-settings-daemon-common
yes | sudo apt install mate-settings-daemon-pulse
yes | sudo apt install mate-system-monitor
yes | sudo apt install mate-system-monitor-common
yes | sudo apt install mate-terminal
yes | sudo apt install mate-terminal-common
yes | sudo apt install mate-themes
yes | sudo apt install mate-utils
yes | sudo apt install mate-utils-common
yes | sudo apt install mawk
yes | sudo apt install menu
yes | sudo apt install menu-xdg
yes | sudo apt install mercurial
yes | sudo apt install mercurial-common
yes | sudo apt install mesa-common-dev
yes | sudo apt install mime-support
yes | sudo apt install mlocate
yes | sudo apt install mobile-broadband-provider-info
yes | sudo apt install modemmanager
yes | sudo apt install mount
yes | sudo apt install mscompress
yes | sudo apt install multiarch-support
yes | sudo apt install murrine-themes
yes | sudo apt install mutt
yes | sudo apt install mysql-common
yes | sudo apt install mythes-en-us
yes | sudo apt install nano
yes | sudo apt install ncurses-base
yes | sudo apt install ncurses-bin
yes | sudo apt install ncurses-term
yes | sudo apt install nepomuk-core-data
yes | sudo apt install net-tools
yes | sudo apt install netbase
yes | sudo apt install netcat
yes | sudo apt install netcat-traditional
yes | sudo apt install netselect
yes | sudo apt install netselect-apt
yes | sudo apt install network-manager
yes | sudo apt install network-manager-gnome
yes | sudo apt install nfacct
yes | sudo apt install nfs-common
yes | sudo apt install nginx
yes | sudo apt install nginx-common
yes | sudo apt install nginx-full
yes | sudo apt install notification-daemon
yes | sudo apt install ntfs-3g
yes | sudo apt install ntrack-module-libnl-0
yes | sudo apt install openbios-ppc
yes | sudo apt install openbios-sparc
yes | sudo apt install openhackware
yes | sudo apt install openjdk-7-jre
yes | sudo apt install openjdk-7-jre-headless
yes | sudo apt install openprinting-ppds
yes | sudo apt install openssh-client
yes | sudo apt install openssl
yes | sudo apt install oracle-java8-installer
yes | sudo apt install oracle-java8-set-default
yes | sudo apt install os-prober
yes | sudo apt install oxygen-icon-theme
yes | sudo apt install p11-kit
yes | sudo apt install p11-kit-modules
yes | sudo apt install p7zip-full
yes | sudo apt install parted
yes | sudo apt install passwd
yes | sudo apt install patch
yes | sudo apt install pciutils
yes | sudo apt install perl
yes | sudo apt install perl-base
yes | sudo apt install perl-modules
yes | sudo apt install phonon
yes | sudo apt install phonon-backend-vlc
yes | sudo apt install pinentry-gtk2
yes | sudo apt install plasma-scriptengine-javascript
yes | sudo apt install pluma
yes | sudo apt install pluma-common
yes | sudo apt install policykit-1
yes | sudo apt install policykit-1-gnome
yes | sudo apt install poppler-data
yes | sudo apt install poppler-utils
yes | sudo apt install popularity-contest
yes | sudo apt install powermgmt-base
yes | sudo apt install ppp
yes | sudo apt install printer-driver-all
yes | sudo apt install printer-driver-brlaser
yes | sudo apt install printer-driver-c2050
yes | sudo apt install printer-driver-c2esp
yes | sudo apt install printer-driver-cjet
yes | sudo apt install printer-driver-dymo
yes | sudo apt install printer-driver-escpr
yes | sudo apt install printer-driver-foo2zjs
yes | sudo apt install printer-driver-foo2zjs-common
yes | sudo apt install printer-driver-gutenprint
yes | sudo apt install printer-driver-hpcups
yes | sudo apt install printer-driver-hpijs
yes | sudo apt install printer-driver-m2300w
yes | sudo apt install printer-driver-min12xxw
yes | sudo apt install printer-driver-pnm2ppa
yes | sudo apt install printer-driver-postscript-hp
yes | sudo apt install printer-driver-ptouch
yes | sudo apt install printer-driver-pxljr
yes | sudo apt install printer-driver-sag-gdi
yes | sudo apt install printer-driver-splix
yes | sudo apt install procmail
yes | sudo apt install procps
yes | sudo apt install psmisc
yes | sudo apt install pulseaudio
yes | sudo apt install pulseaudio-module-x11
yes | sudo apt install pulseaudio-utils
yes | sudo apt install python
yes | sudo apt install python-apt
yes | sudo apt install python-apt-common
yes | sudo apt install python-cairo
yes | sudo apt install python-chardet
yes | sudo apt install python-dbus
yes | sudo apt install python-dbus-dev
yes | sudo apt install python-debian
yes | sudo apt install python-debianbts
yes | sudo apt install python-defusedxml
yes | sudo apt install python-docutils
yes | sudo apt install python-gi
yes | sudo apt install python-gobject
yes | sudo apt install python-gobject-2
yes | sudo apt install python-gst0.10
yes | sudo apt install python-gtk2
yes | sudo apt install python-imaging
yes | sudo apt install python-iniparse
yes | sudo apt install python-libxml2
yes | sudo apt install python-minimal
yes | sudo apt install python-notify
yes | sudo apt install python-numpy
yes | sudo apt install python-pexpect
yes | sudo apt install python-pil
yes | sudo apt install python-pkg-resources
yes | sudo apt install python-pygments
yes | sudo apt install python-qscintilla2
yes | sudo apt install python-qt4
yes | sudo apt install python-renderpm
yes | sudo apt install python-reportbug
yes | sudo apt install python-reportlab
yes | sudo apt install python-reportlab-accel
yes | sudo apt install python-roman
yes | sudo apt install python-sip
yes | sudo apt install python-six
yes | sudo apt install python-soappy
yes | sudo apt install python-support
yes | sudo apt install python-talloc
yes | sudo apt install python-wstools
yes | sudo apt install python2.7
yes | sudo apt install python2.7-minimal
yes | sudo apt install python3
yes | sudo apt install python3-brlapi
yes | sudo apt install python3-cairo
yes | sudo apt install python3-gi
yes | sudo apt install python3-louis
yes | sudo apt install python3-minimal
yes | sudo apt install python3-pyatspi
yes | sudo apt install python3-speechd
yes | sudo apt install python3-xdg
yes | sudo apt install python3.4
yes | sudo apt install python3.4-minimal
yes | sudo apt install qdbus
yes | sudo apt install qemu
yes | sudo apt install qemu-slof
yes | sudo apt install qemu-system
yes | sudo apt install qemu-system-arm
yes | sudo apt install qemu-system-common
yes | sudo apt install qemu-system-mips
yes | sudo apt install qemu-system-misc
yes | sudo apt install qemu-system-ppc
yes | sudo apt install qemu-system-sparc
yes | sudo apt install qemu-system-x86
yes | sudo apt install qemu-user
yes | sudo apt install qemu-user-static
yes | sudo apt install qemu-utils
yes | sudo apt install qpdf
yes | sudo apt install qt-at-spi
yes | sudo apt install qt4-designer
yes | sudo apt install qt4-dev-tools
yes | sudo apt install qt4-doc
yes | sudo apt install qt4-linguist-tools
yes | sudo apt install qt4-qmake
yes | sudo apt install qtchooser
yes | sudo apt install qtcore4-l10n
yes | sudo apt install rarian-compat
yes | sudo apt install readline-common
yes | sudo apt install rename
yes | sudo apt install reportbug
yes | sudo apt install rpcbind
yes | sudo apt install rsync
yes | sudo apt install rsyslog
yes | sudo apt install rtkit
yes | sudo apt install samba-libs
yes | sudo apt install sane-utils
yes | sudo apt install seabios
yes | sudo apt install sed
yes | sudo apt install sensible-utils
yes | sudo apt install sgml-base
yes | sudo apt install sgml-data
yes | sudo apt install shared-mime-info
yes | sudo apt install sharutils
yes | sudo apt install soprano-daemon
yes | sudo apt install sound-theme-freedesktop
yes | sudo apt install speech-dispatcher
yes | sudo apt install speech-dispatcher-audio-plugins
yes | sudo apt install sshfs
yes | sudo apt install ssl-cert
yes | sudo apt install startpar
yes | sudo apt install sudo
yes | sudo apt install synaptic
yes | sudo apt install systemd
yes | sudo apt install systemd-sysv
yes | sudo apt install sysv-rc
yes | sudo apt install sysvinit-utils
yes | sudo apt install tar
yes | sudo apt install task-desktop
yes | sudo apt install task-english
yes | sudo apt install task-mate-desktop
yes | sudo apt install task-print-server
yes | sudo apt install tasksel
yes | sudo apt install tasksel-data
yes | sudo apt install tcl
yes | sudo apt install tcl8.6
yes | sudo apt install tcpd
yes | sudo apt install telnet
yes | sudo apt install testdisk
yes | sudo apt install texinfo
yes | sudo apt install time
yes | sudo apt install tk
yes | sudo apt install tk8.6
yes | sudo apt install tortoisehg
yes | sudo apt install traceroute
yes | sudo apt install tzdata
yes | sudo apt install tzdata-java
yes | sudo apt install ucf
yes | sudo apt install udev
yes | sudo apt install udisks
yes | sudo apt install udisks2
yes | sudo apt install unar
yes | sudo apt install uno-libs3
yes | sudo apt install unrar-free
yes | sudo apt install unzip
yes | sudo apt install update-inetd
yes | sudo apt install upower
yes | sudo apt install usb-modeswitch
yes | sudo apt install usb-modeswitch-data
yes | sudo apt install usbmuxd
yes | sudo apt install usbutils
yes | sudo apt install util-linux
yes | sudo apt install util-linux-locales
yes | sudo apt install va-driver-all
yes | sudo apt install vdpau-va-driver
yes | sudo apt install vim-common
yes | sudo apt install vim-tiny
yes | sudo apt install vlc
yes | sudo apt install vlc-data
yes | sudo apt install vlc-nox
yes | sudo apt install vlc-plugin-notify
yes | sudo apt install vlc-plugin-pulse
yes | sudo apt install vlc-plugin-samba
yes | sudo apt install vsftpd
yes | sudo apt install w3m
yes | sudo apt install wamerican
yes | sudo apt install wget
yes | sudo apt install whiptail
yes | sudo apt install whois
yes | sudo apt install wireless-regdb
yes | sudo apt install wpasupplicant
yes | sudo apt install x11-apps
yes | sudo apt install x11-common
yes | sudo apt install x11-session-utils
yes | sudo apt install x11-utils
yes | sudo apt install x11-xkb-utils
yes | sudo apt install x11-xserver-utils
yes | sudo apt install x11proto-core-dev
yes | sudo apt install x11proto-damage-dev
yes | sudo apt install x11proto-dri2-dev
yes | sudo apt install x11proto-fixes-dev
yes | sudo apt install x11proto-gl-dev
yes | sudo apt install x11proto-input-dev
yes | sudo apt install x11proto-kb-dev
yes | sudo apt install x11proto-xext-dev
yes | sudo apt install x11proto-xf86vidmode-dev
yes | sudo apt install xauth
yes | sudo apt install xbitmaps
yes | sudo apt install xbrlapi
yes | sudo apt install xdg-user-dirs
yes | sudo apt install xdg-utils
yes | sudo apt install xfonts-100dpi
yes | sudo apt install xfonts-75dpi
yes | sudo apt install xfonts-base
yes | sudo apt install xfonts-encodings
yes | sudo apt install xfonts-scalable
yes | sudo apt install xfonts-utils
yes | sudo apt install xinit
yes | sudo apt install xkb-data
yes | sudo apt install xml-core
yes | sudo apt install xorg
yes | sudo apt install xorg-docs-core
yes | sudo apt install xorg-sgml-doctools
yes | sudo apt install xserver-common
yes | sudo apt install xserver-xorg
yes | sudo apt install xserver-xorg-core
yes | sudo apt install xserver-xorg-input-all
yes | sudo apt install xserver-xorg-input-evdev
yes | sudo apt install xserver-xorg-input-mouse
yes | sudo apt install xserver-xorg-input-synaptics
yes | sudo apt install xserver-xorg-input-vmmouse
yes | sudo apt install xserver-xorg-input-wacom
yes | sudo apt install xserver-xorg-video-all
yes | sudo apt install xserver-xorg-video-ati
yes | sudo apt install xserver-xorg-video-cirrus
yes | sudo apt install xserver-xorg-video-fbdev
yes | sudo apt install xserver-xorg-video-geode
yes | sudo apt install xserver-xorg-video-intel
yes | sudo apt install xserver-xorg-video-mach64
yes | sudo apt install xserver-xorg-video-mga
yes | sudo apt install xserver-xorg-video-modesetting
yes | sudo apt install xserver-xorg-video-neomagic
yes | sudo apt install xserver-xorg-video-nouveau
yes | sudo apt install xserver-xorg-video-openchrome
yes | sudo apt install xserver-xorg-video-qxl
yes | sudo apt install xserver-xorg-video-r128
yes | sudo apt install xserver-xorg-video-radeon
yes | sudo apt install xserver-xorg-video-savage
yes | sudo apt install xserver-xorg-video-siliconmotion
yes | sudo apt install xserver-xorg-video-sisusb
yes | sudo apt install xserver-xorg-video-tdfx
yes | sudo apt install xserver-xorg-video-trident
yes | sudo apt install xserver-xorg-video-vesa
yes | sudo apt install xserver-xorg-video-vmware
yes | sudo apt install xsltproc
yes | sudo apt install xterm
yes | sudo apt install xtrans-dev
yes | sudo apt install xz-utils
yes | sudo apt install zenity
yes | sudo apt install zenity-common
yes | sudo apt install zip
yes | sudo apt install zlib1g