yes | sudo apt insall acl
yes | sudo apt insall acpi
yes | sudo apt insall acpi-support-base
yes | sudo apt insall acpid
yes | sudo apt insall adduser
yes | sudo apt insall adwaita-icon-theme
yes | sudo apt insall alsa-base
yes | sudo apt insall alsa-utils
yes | sudo apt insall anacron
yes | sudo apt insall apt
yes | sudo apt insall apt-file
yes | sudo apt insall apt-listchanges
yes | sudo apt insall apt-utils
yes | sudo apt insall aptitude
yes | sudo apt insall aptitude-common
yes | sudo apt insall aptitude-doc-en
yes | sudo apt insall arc
yes | sudo apt insall aspell
yes | sudo apt insall aspell-en
yes | sudo apt insall at
yes | sudo apt insall at-spi2-core
yes | sudo apt insall atril
yes | sudo apt insall atril-common
yes | sudo apt insall autoconf
yes | sudo apt insall automake
yes | sudo apt insall autotools-dev
yes | sudo apt insall avahi-daemon
yes | sudo apt insall base-files
yes | sudo apt insall base-passwd
yes | sudo apt insall bash
yes | sudo apt insall bash-completion
yes | sudo apt insall bc
yes | sudo apt insall bind9-host
yes | sudo apt insall binfmt-support
yes | sudo apt insall binutils
yes | sudo apt insall bleachbit
yes | sudo apt insall bsd-mailx
yes | sudo apt insall bsdmainutils
yes | sudo apt insall bsdutils
yes | sudo apt insall build-essential
yes | sudo apt insall busybox
yes | sudo apt insall bzip2
yes | sudo apt insall ca-certificates
yes | sudo apt insall ca-certificates-java
yes | sudo apt insall caja
yes | sudo apt insall caja-common
yes | sudo apt insall cmake
yes | sudo apt insall cmake-data
yes | sudo apt insall coinor-libcbc3
yes | sudo apt insall coinor-libcgl1
yes | sudo apt insall coinor-libclp1
yes | sudo apt insall coinor-libcoinmp1
yes | sudo apt insall coinor-libcoinutils3
yes | sudo apt insall coinor-libosi1
yes | sudo apt insall colord
yes | sudo apt insall colord-data
yes | sudo apt insall console-setup
yes | sudo apt insall console-setup-linux
yes | sudo apt insall coreutils
yes | sudo apt insall cpio
yes | sudo apt insall cpp
yes | sudo apt insall cpp-4.8
yes | sudo apt insall cpp-4.9
yes | sudo apt insall cpufrequtils
yes | sudo apt insall crda
yes | sudo apt insall cron
yes | sudo apt insall cryptsetup-bin
yes | sudo apt insall cups
yes | sudo apt insall cups-browsed
yes | sudo apt insall cups-bsd
yes | sudo apt insall cups-client
yes | sudo apt insall cups-common
yes | sudo apt insall cups-core-drivers
yes | sudo apt insall cups-daemon
yes | sudo apt insall cups-filters
yes | sudo apt insall cups-filters-core-drivers
yes | sudo apt insall cups-ppdc
yes | sudo apt insall cups-server-common
yes | sudo apt insall curl
yes | sudo apt insall dash
yes | sudo apt insall dbus
yes | sudo apt insall dbus-x11
yes | sudo apt insall dc
yes | sudo apt insall dconf-gsettings-backend
yes | sudo apt insall dconf-service
yes | sudo apt insall debconf
yes | sudo apt insall debconf-i18n
yes | sudo apt insall debian-archive-keyring
yes | sudo apt insall debian-faq
yes | sudo apt insall debianutils
yes | sudo apt insall default-jre
yes | sudo apt insall default-jre-headless
yes | sudo apt insall desktop-base
yes | sudo apt insall desktop-file-utils
yes | sudo apt insall dh-python
yes | sudo apt insall dialog
yes | sudo apt insall dictionaries-common
yes | sudo apt insall diffutils
yes | sudo apt insall discover
yes | sudo apt insall discover-data
yes | sudo apt insall dmidecode
yes | sudo apt insall dmsetup
yes | sudo apt insall dmz-cursor-theme
yes | sudo apt insall dns-root-data
yes | sudo apt insall dnsmasq-base
yes | sudo apt insall dnsutils
yes | sudo apt insall doc-debian
yes | sudo apt insall docbook-xml
yes | sudo apt insall docbook-xsl
yes | sudo apt insall docutils-common
yes | sudo apt insall docutils-doc
yes | sudo apt insall dosfstools
yes | sudo apt insall doxygen
yes | sudo apt insall doxygen-gui
yes | sudo apt insall dpkg
yes | sudo apt insall dpkg-dev
yes | sudo apt insall e2fslibs
yes | sudo apt insall e2fsprogs
yes | sudo apt insall eclipse-platform
yes | sudo apt insall eject
yes | sudo apt insall emacsen-common
yes | sudo apt insall enchant
yes | sudo apt insall engrampa
yes | sudo apt insall engrampa-common
yes | sudo apt insall eom
yes | sudo apt insall eom-common
yes | sudo apt insall espeak-data
yes | sudo apt insall exim4
yes | sudo apt insall exim4-base
yes | sudo apt insall exim4-config
yes | sudo apt insall exim4-daemon-light
yes | sudo apt insall extundelete
yes | sudo apt insall fakeroot
yes | sudo apt insall ffmpegthumbnailer
yes | sudo apt insall file
yes | sudo apt insall filezilla
yes | sudo apt insall findutils
yes | sudo apt insall firebird2.5-common
yes | sudo apt insall firebird2.5-server-common
yes | sudo apt insall firefox-esr
yes | sudo apt insall firmware-linux-free
yes | sudo apt insall fontconfig
yes | sudo apt insall fontconfig-config
yes | sudo apt insall fonts-dejavu
yes | sudo apt insall fonts-dejavu-core
yes | sudo apt insall fonts-dejavu-extra
yes | sudo apt insall fonts-droid
yes | sudo apt insall fonts-freefont-ttf
yes | sudo apt insall fonts-liberation
yes | sudo apt insall fonts-sil-gentium
yes | sudo apt insall fonts-sil-gentium-basic
yes | sudo apt insall foomatic-db-compressed-ppds
yes | sudo apt insall foomatic-db-engine
yes | sudo apt insall ftp
yes | sudo apt insall fuse
yes | sudo apt insall g++
yes | sudo apt insall g++-4.9
yes | sudo apt insall galculator
yes | sudo apt insall gawk
yes | sudo apt insall gcc
yes | sudo apt insall gcc-4.8
yes | sudo apt insall gcc-4.8-base
yes | sudo apt insall gcc-4.9
yes | sudo apt insall gcc-4.9-base
yes | sudo apt insall gconf-service
yes | sudo apt insall gconf2
yes | sudo apt insall gconf2-common
yes | sudo apt insall gcr
yes | sudo apt insall gdb
yes | sudo apt insall gdbserver
yes | sudo apt insall gdisk
yes | sudo apt insall geoclue-2.0
yes | sudo apt insall geoip-database
yes | sudo apt insall gettext-base
yes | sudo apt insall ghostscript
yes | sudo apt insall gimp
yes | sudo apt insall gimp-data
yes | sudo apt insall gir1.2-atk-1.0
yes | sudo apt insall gir1.2-atspi-2.0
yes | sudo apt insall gir1.2-freedesktop
yes | sudo apt insall gir1.2-gdkpixbuf-2.0
yes | sudo apt insall gir1.2-glib-2.0
yes | sudo apt insall gir1.2-gtk-2.0
yes | sudo apt insall gir1.2-gtk-3.0
yes | sudo apt insall gir1.2-mate-panel
yes | sudo apt insall gir1.2-pango-1.0
yes | sudo apt insall gir1.2-wnck-3.0
yes | sudo apt insall git
yes | sudo apt insall git-man
yes | sudo apt insall glib-networking
yes | sudo apt insall glib-networking-common
yes | sudo apt insall glib-networking-services
yes | sudo apt insall gnome-accessibility-themes
yes | sudo apt insall gnome-icon-theme
yes | sudo apt insall gnome-icon-theme-symbolic
yes | sudo apt insall gnome-keyring
yes | sudo apt insall gnome-mime-data
yes | sudo apt insall gnome-orca
yes | sudo apt insall gnome-themes-standard
yes | sudo apt insall gnome-themes-standard-data
yes | sudo apt insall gnupg
yes | sudo apt insall gnupg-agent
yes | sudo apt insall gnupg2
yes | sudo apt insall gnustep-base-common
yes | sudo apt insall gnustep-base-runtime
yes | sudo apt insall gnustep-common
yes | sudo apt insall gparted
yes | sudo apt insall gpgv
yes | sudo apt insall grep
yes | sudo apt insall groff-base
yes | sudo apt insall grub-common
yes | sudo apt insall grub-pc
yes | sudo apt insall grub-pc-bin
yes | sudo apt insall grub2-common
yes | sudo apt insall gsettings-desktop-schemas
yes | sudo apt insall gsfonts
yes | sudo apt insall gsfonts-x11
yes | sudo apt insall gstreamer0.10-alsa
yes | sudo apt insall gstreamer0.10-gconf
yes | sudo apt insall gstreamer0.10-plugins-base
yes | sudo apt insall gstreamer0.10-plugins-good
yes | sudo apt insall gstreamer0.10-x
yes | sudo apt insall gstreamer1.0-libav
yes | sudo apt insall gstreamer1.0-plugins-base
yes | sudo apt insall gstreamer1.0-plugins-good
yes | sudo apt insall gstreamer1.0-x
yes | sudo apt insall gtk2-engines
yes | sudo apt insall gtk2-engines-murrine
yes | sudo apt insall gtk2-engines-pixbuf
yes | sudo apt insall gvfs
yes | sudo apt insall gvfs-backends
yes | sudo apt insall gvfs-bin
yes | sudo apt insall gvfs-common
yes | sudo apt insall gvfs-daemons
yes | sudo apt insall gvfs-libs
yes | sudo apt insall gzip
yes | sudo apt insall hdparm
yes | sudo apt insall hicolor-icon-theme
yes | sudo apt insall host
yes | sudo apt insall hostname
yes | sudo apt insall hp-ppd
yes | sudo apt insall hplip
yes | sudo apt insall hplip-data
yes | sudo apt insall htop
yes | sudo apt insall hunspell-en-us
yes | sudo apt insall hyphen-en-us
yes | sudo apt insall i965-va-driver
yes | sudo apt insall iamerican
yes | sudo apt insall ibritish
yes | sudo apt insall iceweasel
yes | sudo apt insall ienglish-common
yes | sudo apt insall ifupdown
yes | sudo apt insall info
yes | sudo apt insall init
yes | sudo apt insall init-system-helpers
yes | sudo apt insall initramfs-tools
yes | sudo apt insall initscripts
yes | sudo apt insall insserv
yes | sudo apt insall install-info
yes | sudo apt insall installation-report
yes | sudo apt insall iproute2
yes | sudo apt insall iptables
yes | sudo apt insall iputils-arping
yes | sudo apt insall iputils-ping
yes | sudo apt insall ipxe-qemu
yes | sudo apt insall irqbalance
yes | sudo apt insall isc-dhcp-client
yes | sudo apt insall isc-dhcp-common
yes | sudo apt insall iso-codes
yes | sudo apt insall ispell
yes | sudo apt insall iw
yes | sudo apt insall java-common
yes | sudo apt insall javascript-common
yes | sudo apt insall kate-data
yes | sudo apt insall katepart
yes | sudo apt insall kbd
yes | sudo apt insall kde-runtime
yes | sudo apt insall kde-runtime-data
yes | sudo apt insall kdelibs-bin
yes | sudo apt insall kdelibs5-data
yes | sudo apt insall kdelibs5-plugins
yes | sudo apt insall kdoctools
yes | sudo apt insall keyboard-configuration
yes | sudo apt insall klibc-utils
yes | sudo apt insall kmod
yes | sudo apt insall konsole
yes | sudo apt insall krb5-locales
yes | sudo apt insall laptop-detect
yes | sudo apt insall leafpad
yes | sudo apt insall less
yes | sudo apt insall liba52-0.7.4
yes | sudo apt insall libaa1
yes | sudo apt insall libaacs0
yes | sudo apt insall libabw-0.1-1
yes | sudo apt insall libacl1
yes | sudo apt insall libaio1
yes | sudo apt insall libalgorithm-c3-perl
yes | sudo apt insall libalgorithm-diff-perl
yes | sudo apt insall libalgorithm-diff-xs-perl
yes | sudo apt insall libalgorithm-merge-perl
yes | sudo apt insall libamd2.3.1
yes | sudo apt insall libao-common
yes | sudo apt insall libao4
yes | sudo apt insall libapt-inst1.5
yes | sudo apt insall libapt-pkg-perl
yes | sudo apt insall libapt-pkg4.12
yes | sudo apt insall libarchive-extract-perl
yes | sudo apt insall libarchive13
yes | sudo apt insall libart-2.0-2
yes | sudo apt insall libasan0
yes | sudo apt insall libasan1
yes | sudo apt insall libasound2
yes | sudo apt insall libasound2-data
yes | sudo apt insall libasound2-plugins
yes | sudo apt insall libaspell15
yes | sudo apt insall libasprintf0c2
yes | sudo apt insall libass5
yes | sudo apt insall libassuan0
yes | sudo apt insall libasyncns0
yes | sudo apt insall libatasmart4
yes | sudo apt insall libatk-adaptor
yes | sudo apt insall libatk-bridge2.0-0
yes | sudo apt insall libatk-wrapper-java
yes | sudo apt insall libatk-wrapper-java-jni
yes | sudo apt insall libatk1.0-0
yes | sudo apt insall libatk1.0-data
yes | sudo apt insall libatkmm-1.6-1
yes | sudo apt insall libatomic1
yes | sudo apt insall libatrildocument3
yes | sudo apt insall libatrilview3
yes | sudo apt insall libatspi2.0-0
yes | sudo apt insall libattica0.4
yes | sudo apt insall libattr1
yes | sudo apt insall libaudio2
yes | sudo apt insall libaudit-common
yes | sudo apt insall libaudit1
yes | sudo apt insall libauthen-sasl-perl
yes | sudo apt insall libavahi-client3
yes | sudo apt insall libavahi-common-data
yes | sudo apt insall libavahi-common3
yes | sudo apt insall libavahi-core7
yes | sudo apt insall libavahi-glib1
yes | sudo apt insall libavc1394-0
yes | sudo apt insall libavcodec56
yes | sudo apt insall libavformat56
yes | sudo apt insall libavresample2
yes | sudo apt insall libavutil54
yes | sudo apt insall libbabl-0.1-0
yes | sudo apt insall libbasicusageenvironment0
yes | sudo apt insall libbind9-90
yes | sudo apt insall libblas-common
yes | sudo apt insall libblas3
yes | sudo apt insall libblkid1
yes | sudo apt insall libbluetooth3
yes | sudo apt insall libbluray1
yes | sudo apt insall libbonobo2-0
yes | sudo apt insall libbonobo2-common
yes | sudo apt insall libbonoboui2-0
yes | sudo apt insall libbonoboui2-common
yes | sudo apt insall libboost-date-time1.55.0
yes | sudo apt insall libboost-iostreams1.55.0
yes | sudo apt insall libboost-system1.55.0
yes | sudo apt insall libboost-thread1.55.0
yes | sudo apt insall libbrlapi0.6
yes | sudo apt insall libbsd0
yes | sudo apt insall libbz2-1.0
yes | sudo apt insall libc-bin
yes | sudo apt insall libc-dev-bin
yes | sudo apt insall libc6
yes | sudo apt insall libc6-dbg
yes | sudo apt insall libc6-dev
yes | sudo apt insall libc6-i686
yes | sudo apt insall libcaca0
yes | sudo apt insall libcairo-gobject2
yes | sudo apt insall libcairo-perl
yes | sudo apt insall libcairo2
yes | sudo apt insall libcairomm-1.0-1
yes | sudo apt insall libcaja-extension1
yes | sudo apt insall libcamd2.3.1
yes | sudo apt insall libcanberra-gtk-module
yes | sudo apt insall libcanberra-gtk0
yes | sudo apt insall libcanberra-gtk3-0
yes | sudo apt insall libcanberra-gtk3-module
yes | sudo apt insall libcanberra0
yes | sudo apt insall libcap-ng0
yes | sudo apt insall libcap2
yes | sudo apt insall libcap2-bin
yes | sudo apt insall libccolamd2.8.0
yes | sudo apt insall libcddb2
yes | sudo apt insall libcdio-cdda1
yes | sudo apt insall libcdio-paranoia1
yes | sudo apt insall libcdio13
yes | sudo apt insall libcdparanoia0
yes | sudo apt insall libcdr-0.1-1
yes | sudo apt insall libcgi-fast-perl
yes | sudo apt insall libcgi-pm-perl
yes | sudo apt insall libcholmod2.1.2
yes | sudo apt insall libchromaprint0
yes | sudo apt insall libcilkrts5
yes | sudo apt insall libclang1-3.5
yes | sudo apt insall libclass-accessor-perl
yes | sudo apt insall libclass-c3-perl
yes | sudo apt insall libclass-c3-xs-perl
yes | sudo apt insall libclass-isa-perl
yes | sudo apt insall libcloog-isl4
yes | sudo apt insall libclucene-contribs1
yes | sudo apt insall libclucene-core1
yes | sudo apt insall libcmis-0.4-4
yes | sudo apt insall libcolamd2.8.0
yes | sudo apt insall libcolord2
yes | sudo apt insall libcolorhug2
yes | sudo apt insall libcomerr2
yes | sudo apt insall libconfig-file-perl
yes | sudo apt insall libcpan-meta-perl
yes | sudo apt insall libcpufreq0
yes | sudo apt insall libcroco3
yes | sudo apt insall libcryptsetup4
yes | sudo apt insall libcrystalhd3
yes | sudo apt insall libcups2
yes | sudo apt insall libcupscgi1
yes | sudo apt insall libcupsfilters1
yes | sudo apt insall libcupsimage2
yes | sudo apt insall libcupsmime1
yes | sudo apt insall libcupsppdc1
yes | sudo apt insall libcurl3
yes | sudo apt insall libcurl3-gnutls
yes | sudo apt insall libcwidget3
yes | sudo apt insall libdaemon0
yes | sudo apt insall libdata-optlist-perl
yes | sudo apt insall libdata-section-perl
yes | sudo apt insall libdatrie1
yes | sudo apt insall libdb5.3
yes | sudo apt insall libdb5.3-java
yes | sudo apt insall libdb5.3-java-jni
yes | sudo apt insall libdbus-1-3
yes | sudo apt insall libdbus-glib-1-2
yes | sudo apt insall libdbusmenu-qt2
yes | sudo apt insall libdc1394-22
yes | sudo apt insall libdca0
yes | sudo apt insall libdconf1
yes | sudo apt insall libdebconfclient0
yes | sudo apt insall libdevmapper-event1.02.1
yes | sudo apt insall libdevmapper1.02.1
yes | sudo apt insall libdirectfb-1.2-9
yes | sudo apt insall libdiscover2
yes | sudo apt insall libdjvulibre-text
yes | sudo apt insall libdjvulibre21
yes | sudo apt insall libdlrestrictions1
yes | sudo apt insall libdns-export100
yes | sudo apt insall libdns100
yes | sudo apt insall libdotconf0
yes | sudo apt insall libdpkg-perl
yes | sudo apt insall libdrm-dev
yes | sudo apt insall libdrm-intel1
yes | sudo apt insall libdrm-nouveau2
yes | sudo apt insall libdrm-radeon1
yes | sudo apt insall libdrm2
yes | sudo apt insall libdv4
yes | sudo apt insall libdvbpsi9
yes | sudo apt insall libdvdnav4
yes | sudo apt insall libdvdread4
yes | sudo apt insall libe-book-0.1-1
yes | sudo apt insall libebml4
yes | sudo apt insall libedit2
yes | sudo apt insall libegl1-mesa
yes | sudo apt insall libegl1-mesa-drivers
yes | sudo apt insall libelf1
yes | sudo apt insall libelfg0
yes | sudo apt insall libenca0
yes | sudo apt insall libenchant1c2a
yes | sudo apt insall libencode-locale-perl
yes | sudo apt insall libeot0
yes | sudo apt insall libepoxy0
yes | sudo apt insall libept1.4.12
yes | sudo apt insall liberror-perl
yes | sudo apt insall libespeak1
yes | sudo apt insall libestr0
yes | sudo apt insall libetonyek-0.1-1
yes | sudo apt insall libevdev2
yes | sudo apt insall libevent-2.0-5
yes | sudo apt insall libexempi3
yes | sudo apt insall libexif12
yes | sudo apt insall libexiv2-13
yes | sudo apt insall libexpat1
yes | sudo apt insall libexpat1-dev
yes | sudo apt insall libexttextcat-2.0-0
yes | sudo apt insall libfaad2
yes | sudo apt insall libfakeroot
yes | sudo apt insall libfam0
yes | sudo apt insall libfbclient2
yes | sudo apt insall libfbembed2.5
yes | sudo apt insall libfcgi-perl
yes | sudo apt insall libfdt1
yes | sudo apt insall libffi6
yes | sudo apt insall libffmpegthumbnailer4
yes | sudo apt insall libfftw3-single3
yes | sudo apt insall libfile-basedir-perl
yes | sudo apt insall libfile-copy-recursive-perl
yes | sudo apt insall libfile-desktopentry-perl
yes | sudo apt insall libfile-fcntllock-perl
yes | sudo apt insall libfile-listing-perl
yes | sudo apt insall libfile-mimeinfo-perl
yes | sudo apt insall libflac8
yes | sudo apt insall libflite1
yes | sudo apt insall libfont-afm-perl
yes | sudo apt insall libfontconfig1
yes | sudo apt insall libfontembed1
yes | sudo apt insall libfontenc1
yes | sudo apt insall libfreehand-0.1-1
yes | sudo apt insall libfreerdp-cache1.1
yes | sudo apt insall libfreerdp-client1.1
yes | sudo apt insall libfreerdp-codec1.1
yes | sudo apt insall libfreerdp-common1.1.0
yes | sudo apt insall libfreerdp-core1.1
yes | sudo apt insall libfreerdp-crypto1.1
yes | sudo apt insall libfreerdp-gdi1.1
yes | sudo apt insall libfreerdp-locale1.1
yes | sudo apt insall libfreerdp-primitives1.1
yes | sudo apt insall libfreerdp-rail1.1
yes | sudo apt insall libfreerdp-utils1.1
yes | sudo apt insall libfreetype6
yes | sudo apt insall libfribidi0
yes | sudo apt insall libfuse2
yes | sudo apt insall libgail-common
yes | sudo apt insall libgail18
yes | sudo apt insall libgbm1
yes | sudo apt insall libgc1c2
yes | sudo apt insall libgcc-4.8-dev
yes | sudo apt insall libgcc-4.9-dev
yes | sudo apt insall libgcc1
yes | sudo apt insall libgck-1-0
yes | sudo apt insall libgconf-2-4
yes | sudo apt insall libgconf2-4
yes | sudo apt insall libgcr-3-common
yes | sudo apt insall libgcr-base-3-1
yes | sudo apt insall libgcr-ui-3-1
yes | sudo apt insall libgcrypt20
yes | sudo apt insall libgd3
yes | sudo apt insall libgdbm3
yes | sudo apt insall libgdk-pixbuf2.0-0
yes | sudo apt insall libgdk-pixbuf2.0-common
yes | sudo apt insall libgegl-0.2-0
yes | sudo apt insall libgeoip1
yes | sudo apt insall libgfortran3
yes | sudo apt insall libgif4
yes | sudo apt insall libgimp2.0
yes | sudo apt insall libgirepository-1.0-1
yes | sudo apt insall libgksu2-0
yes | sudo apt insall libgl1-mesa-dev
yes | sudo apt insall libgl1-mesa-dri
yes | sudo apt insall libgl1-mesa-glx
yes | sudo apt insall libglade2-0
yes | sudo apt insall libglapi-mesa
yes | sudo apt insall libgles1-mesa
yes | sudo apt insall libgles2-mesa
yes | sudo apt insall libglew1.10
yes | sudo apt insall libglib-perl
yes | sudo apt insall libglib2.0-0
yes | sudo apt insall libglib2.0-bin
yes | sudo apt insall libglib2.0-data
yes | sudo apt insall libglibmm-2.4-1c2a
yes | sudo apt insall libgltf-0.0-0
yes | sudo apt insall libglu1-mesa
yes | sudo apt insall libglu1-mesa-dev
yes | sudo apt insall libgmp10
yes | sudo apt insall libgnome-2-0
yes | sudo apt insall libgnome-keyring-common
yes | sudo apt insall libgnome-keyring0
yes | sudo apt insall libgnome2-0
yes | sudo apt insall libgnome2-bin
yes | sudo apt insall libgnome2-common
yes | sudo apt insall libgnomecanvas2-0
yes | sudo apt insall libgnomecanvas2-common
yes | sudo apt insall libgnomeui-0
yes | sudo apt insall libgnomeui-common
yes | sudo apt insall libgnomevfs2-0
yes | sudo apt insall libgnomevfs2-common
yes | sudo apt insall libgnomevfs2-extra
yes | sudo apt insall libgnustep-base1.24
yes | sudo apt insall libgnutls-deb0-28
yes | sudo apt insall libgnutls-openssl27
yes | sudo apt insall libgoa-1.0-0b
yes | sudo apt insall libgoa-1.0-common
yes | sudo apt insall libgomp1
yes | sudo apt insall libgpg-error0
yes | sudo apt insall libgpgme++2
yes | sudo apt insall libgpgme11
yes | sudo apt insall libgphoto2-6
yes | sudo apt insall libgphoto2-l10n
yes | sudo apt insall libgphoto2-port10
yes | sudo apt insall libgpm2
yes | sudo apt insall libgraphite2-3
yes | sudo apt insall libgroupsock1
yes | sudo apt insall libgs9
yes | sudo apt insall libgs9-common
yes | sudo apt insall libgsm1
yes | sudo apt insall libgssapi-krb5-2
yes | sudo apt insall libgstreamer-plugins-base0.10-0
yes | sudo apt insall libgstreamer-plugins-base1.0-0
yes | sudo apt insall libgstreamer0.10-0
yes | sudo apt insall libgstreamer1.0-0
yes | sudo apt insall libgtk-3-0
yes | sudo apt insall libgtk-3-bin
yes | sudo apt insall libgtk-3-common
yes | sudo apt insall libgtk2-perl
yes | sudo apt insall libgtk2.0-0
yes | sudo apt insall libgtk2.0-bin
yes | sudo apt insall libgtk2.0-common
yes | sudo apt insall libgtkmm-2.4-1c2a
yes | sudo apt insall libgtksourceview2.0-0
yes | sudo apt insall libgtksourceview2.0-common
yes | sudo apt insall libgtop2-7
yes | sudo apt insall libgtop2-common
yes | sudo apt insall libgudev-1.0-0
yes | sudo apt insall libgusb2
yes | sudo apt insall libgutenprint2
yes | sudo apt insall libgxps2
yes | sudo apt insall libharfbuzz-icu0
yes | sudo apt insall libharfbuzz0b
yes | sudo apt insall libhogweed2
yes | sudo apt insall libhpmud0
yes | sudo apt insall libhtml-form-perl
yes | sudo apt insall libhtml-format-perl
yes | sudo apt insall libhtml-parser-perl
yes | sudo apt insall libhtml-tagset-perl
yes | sudo apt insall libhtml-tree-perl
yes | sudo apt insall libhttp-cookies-perl
yes | sudo apt insall libhttp-daemon-perl
yes | sudo apt insall libhttp-date-perl
yes | sudo apt insall libhttp-message-perl
yes | sudo apt insall libhttp-negotiate-perl
yes | sudo apt insall libhunspell-1.3-0
yes | sudo apt insall libhyphen0
yes | sudo apt insall libice6
yes | sudo apt insall libicu52
yes | sudo apt insall libidn11
yes | sudo apt insall libiec61883-0
yes | sudo apt insall libieee1284-3
yes | sudo apt insall libijs-0.35
yes | sudo apt insall libilmbase6
yes | sudo apt insall libimobiledevice4
yes | sudo apt insall libintl-perl
yes | sudo apt insall libio-html-perl
yes | sudo apt insall libio-socket-ip-perl
yes | sudo apt insall libio-socket-ssl-perl
yes | sudo apt insall libio-string-perl
yes | sudo apt insall libiodbc2
yes | sudo apt insall libirs-export91
yes | sudo apt insall libisc-export95
yes | sudo apt insall libisc95
yes | sudo apt insall libisccc90
yes | sudo apt insall libisccfg-export90
yes | sudo apt insall libisccfg90
yes | sudo apt insall libiscsi2
yes | sudo apt insall libisl10
yes | sudo apt insall libiso9660-8
yes | sudo apt insall libitm1
yes | sudo apt insall libjack-jackd2-0
yes | sudo apt insall libjasper1
yes | sudo apt insall libjavascriptcoregtk-3.0-0
yes | sudo apt insall libjbig0
yes | sudo apt insall libjbig2dec0
yes | sudo apt insall libjim0.75
yes | sudo apt insall libjpeg62-turbo
yes | sudo apt insall libjs-excanvas
yes | sudo apt insall libjs-jquery
yes | sudo apt insall libjs-underscore
yes | sudo apt insall libjson-c2
yes | sudo apt insall libjson-glib-1.0-0
yes | sudo apt insall libjson-glib-1.0-common
yes | sudo apt insall libk5crypto3
yes | sudo apt insall libkactivities-bin
yes | sudo apt insall libkactivities-models1
yes | sudo apt insall libkactivities6
yes | sudo apt insall libkate1
yes | sudo apt insall libkatepartinterfaces4
yes | sudo apt insall libkcmutils4
yes | sudo apt insall libkde3support4
yes | sudo apt insall libkdeclarative5
yes | sudo apt insall libkdecore5
yes | sudo apt insall libkdesu5
yes | sudo apt insall libkdeui5
yes | sudo apt insall libkdewebkit5
yes | sudo apt insall libkdnssd4
yes | sudo apt insall libkemoticons4
yes | sudo apt insall libkeyutils1
yes | sudo apt insall libkfile4
yes | sudo apt insall libkhtml5
yes | sudo apt insall libkio5
yes | sudo apt insall libkjsapi4
yes | sudo apt insall libkjsembed4
yes | sudo apt insall libklibc
yes | sudo apt insall libkmediaplayer4
yes | sudo apt insall libkmod2
yes | sudo apt insall libknewstuff3-4
yes | sudo apt insall libknotifyconfig4
yes | sudo apt insall libkntlm4
yes | sudo apt insall libkonq-common
yes | sudo apt insall libkonq5-templates
yes | sudo apt insall libkonq5abi1
yes | sudo apt insall libkparts4
yes | sudo apt insall libkpathsea6
yes | sudo apt insall libkpty4
yes | sudo apt insall libkrb5-3
yes | sudo apt insall libkrb5support0
yes | sudo apt insall libkrosscore4
yes | sudo apt insall libksba8
yes | sudo apt insall libktexteditor4
yes | sudo apt insall libkxmlrpcclient4
yes | sudo apt insall liblangtag1
yes | sudo apt insall liblapack3
yes | sudo apt insall liblcms2-2
yes | sudo apt insall liblcms2-utils
yes | sudo apt insall libldap-2.4-2
yes | sudo apt insall libldb1
yes | sudo apt insall liblightdm-gobject-1-0
yes | sudo apt insall liblircclient0
yes | sudo apt insall liblist-moreutils-perl
yes | sudo apt insall liblivemedia23
yes | sudo apt insall libllvm3.5
yes | sudo apt insall liblocale-gettext-perl
yes | sudo apt insall liblockfile-bin
yes | sudo apt insall liblockfile1
yes | sudo apt insall liblog-message-perl
yes | sudo apt insall liblog-message-simple-perl
yes | sudo apt insall liblogging-stdlog0
yes | sudo apt insall liblognorm1
yes | sudo apt insall liblouis-data
yes | sudo apt insall liblouis2
yes | sudo apt insall libltdl-dev
yes | sudo apt insall libltdl7
yes | sudo apt insall liblua5.2-0
yes | sudo apt insall liblvm2app2.2
yes | sudo apt insall liblwp-mediatypes-perl
yes | sudo apt insall liblwp-protocol-https-perl
yes | sudo apt insall liblwres90
yes | sudo apt insall liblzma5
yes | sudo apt insall liblzo2-2
yes | sudo apt insall libmad0
yes | sudo apt insall libmagic1
yes | sudo apt insall libmailtools-perl
yes | sudo apt insall libmarco-private0
yes | sudo apt insall libmate-desktop-2-17
yes | sudo apt insall libmate-menu2
yes | sudo apt insall libmate-panel-applet-4-1
yes | sudo apt insall libmate-slab0
yes | sudo apt insall libmate-window-settings1
yes | sudo apt insall libmatedict6
yes | sudo apt insall libmatekbd-common
yes | sudo apt insall libmatekbd4
yes | sudo apt insall libmateweather-common
yes | sudo apt insall libmateweather1
yes | sudo apt insall libmatroska6
yes | sudo apt insall libmbim-glib4
yes | sudo apt insall libmbim-proxy
yes | sudo apt insall libmhash2
yes | sudo apt insall libmm-glib0
yes | sudo apt insall libmng1
yes | sudo apt insall libmnl0
yes | sudo apt insall libmodplug1
yes | sudo apt insall libmodule-build-perl
yes | sudo apt insall libmodule-pluggable-perl
yes | sudo apt insall libmodule-signature-perl
yes | sudo apt insall libmount1
yes | sudo apt insall libmp3lame0
yes | sudo apt insall libmpc3
yes | sudo apt insall libmpcdec6
yes | sudo apt insall libmpdec2
yes | sudo apt insall libmpeg2-4
yes | sudo apt insall libmpfr4
yes | sudo apt insall libmro-compat-perl
yes | sudo apt insall libmspub-0.1-1
yes | sudo apt insall libmtdev1
yes | sudo apt insall libmtp-common
yes | sudo apt insall libmtp-runtime
yes | sudo apt insall libmtp9
yes | sudo apt insall libmwaw-0.3-3
yes | sudo apt insall libmysqlclient18
yes | sudo apt insall libmythes-1.2-0
yes | sudo apt insall libncurses5
yes | sudo apt insall libncursesw5
yes | sudo apt insall libndp0
yes | sudo apt insall libneon27-gnutls
yes | sudo apt insall libnepomuk4
yes | sudo apt insall libnepomukcore4
yes | sudo apt insall libnepomukquery4a
yes | sudo apt insall libnepomukutils4
yes | sudo apt insall libnet-dbus-perl
yes | sudo apt insall libnet-http-perl
yes | sudo apt insall libnet-smtp-ssl-perl
yes | sudo apt insall libnet-ssleay-perl
yes | sudo apt insall libnetfilter-acct1
yes | sudo apt insall libnetfilter-conntrack3
yes | sudo apt insall libnettle4
yes | sudo apt insall libnewt0.52
yes | sudo apt insall libnfnetlink0
yes | sudo apt insall libnfsidmap2
yes | sudo apt insall libnl-3-200
yes | sudo apt insall libnl-genl-3-200
yes | sudo apt insall libnl-route-3-200
yes | sudo apt insall libnm-glib-vpn1
yes | sudo apt insall libnm-glib4
yes | sudo apt insall libnm-gtk-common
yes | sudo apt insall libnm-gtk0
yes | sudo apt insall libnm-util2
yes | sudo apt insall libnotify4
yes | sudo apt insall libnspr4
yes | sudo apt insall libnss-mdns
yes | sudo apt insall libnss3
yes | sudo apt insall libntdb1
yes | sudo apt insall libntrack-qt4-1
yes | sudo apt insall libntrack0
yes | sudo apt insall libnuma1
yes | sudo apt insall libobjc-4.9-dev
yes | sudo apt insall libobjc4
yes | sudo apt insall libodfgen-0.1-1
yes | sudo apt insall libogg0
yes | sudo apt insall libopenexr6
yes | sudo apt insall libopenjpeg5
yes | sudo apt insall libopenraw1
yes | sudo apt insall libopenvg1-mesa
yes | sudo apt insall libopus0
yes | sudo apt insall liborbit-2-0
yes | sudo apt insall liborc-0.4-0
yes | sudo apt insall liborcus-0.8-0
yes | sudo apt insall libp11-kit0
yes | sudo apt insall libpackage-constants-perl
yes | sudo apt insall libpam-gnome-keyring
yes | sudo apt insall libpam-modules
yes | sudo apt insall libpam-modules-bin
yes | sudo apt insall libpam-runtime
yes | sudo apt insall libpam-systemd
yes | sudo apt insall libpam0g
yes | sudo apt insall libpango-1.0-0
yes | sudo apt insall libpango-perl
yes | sudo apt insall libpango1.0-0
yes | sudo apt insall libpangocairo-1.0-0
yes | sudo apt insall libpangoft2-1.0-0
yes | sudo apt insall libpangomm-1.4-1
yes | sudo apt insall libpangox-1.0-0
yes | sudo apt insall libpangoxft-1.0-0
yes | sudo apt insall libpaper-utils
yes | sudo apt insall libpaper1
yes | sudo apt insall libparams-util-perl
yes | sudo apt insall libparse-debianchangelog-perl
yes | sudo apt insall libparted-fs-resize0
yes | sudo apt insall libparted2
yes | sudo apt insall libpcap0.8
yes | sudo apt insall libpci3
yes | sudo apt insall libpciaccess0
yes | sudo apt insall libpcre3
yes | sudo apt insall libpcsclite1
yes | sudo apt insall libperl4-corelibs-perl
yes | sudo apt insall libperl5.20
yes | sudo apt insall libphonon4
yes | sudo apt insall libpipeline1
yes | sudo apt insall libpixman-1-0
yes | sudo apt insall libplasma3
yes | sudo apt insall libplist2
yes | sudo apt insall libpng12-0
yes | sudo apt insall libpod-latex-perl
yes | sudo apt insall libpod-readme-perl
yes | sudo apt insall libpolkit-agent-1-0
yes | sudo apt insall libpolkit-backend-1-0
yes | sudo apt insall libpolkit-gobject-1-0
yes | sudo apt insall libpolkit-qt-1-1
yes | sudo apt insall libpoppler-glib8
yes | sudo apt insall libpoppler46
yes | sudo apt insall libpopt0
yes | sudo apt insall libportaudio2
yes | sudo apt insall libpostproc52
yes | sudo apt insall libprocps3
yes | sudo apt insall libproxy-tools
yes | sudo apt insall libproxy1
yes | sudo apt insall libpsl0
yes | sudo apt insall libpth20
yes | sudo apt insall libpthread-stubs0-dev
yes | sudo apt insall libpulse-mainloop-glib0
yes | sudo apt insall libpulse0
yes | sudo apt insall libpulsedsp
yes | sudo apt insall libpython-dev
yes | sudo apt insall libpython-stdlib
yes | sudo apt insall libpython2.7
yes | sudo apt insall libpython2.7-dev
yes | sudo apt insall libpython2.7-minimal
yes | sudo apt insall libpython2.7-stdlib
yes | sudo apt insall libpython3-stdlib
yes | sudo apt insall libpython3.4
yes | sudo apt insall libpython3.4-minimal
yes | sudo apt insall libpython3.4-stdlib
yes | sudo apt insall libqca2
yes | sudo apt insall libqmi-glib1
yes | sudo apt insall libqmi-proxy
yes | sudo apt insall libqpdf13
yes | sudo apt insall libqscintilla2-11
yes | sudo apt insall libqscintilla2-l10n
yes | sudo apt insall libqt4-core
yes | sudo apt insall libqt4-dbus
yes | sudo apt insall libqt4-declarative
yes | sudo apt insall libqt4-designer
yes | sudo apt insall libqt4-dev
yes | sudo apt insall libqt4-dev-bin
yes | sudo apt insall libqt4-gui
yes | sudo apt insall libqt4-help
yes | sudo apt insall libqt4-network
yes | sudo apt insall libqt4-opengl
yes | sudo apt insall libqt4-opengl-dev
yes | sudo apt insall libqt4-qt3support
yes | sudo apt insall libqt4-script
yes | sudo apt insall libqt4-scripttools
yes | sudo apt insall libqt4-sql
yes | sudo apt insall libqt4-sql-mysql
yes | sudo apt insall libqt4-sql-sqlite
yes | sudo apt insall libqt4-svg
yes | sudo apt insall libqt4-test
yes | sudo apt insall libqt4-xml
yes | sudo apt insall libqt4-xmlpatterns
yes | sudo apt insall libqtassistantclient4
yes | sudo apt insall libqtcore4
yes | sudo apt insall libqtdbus4
yes | sudo apt insall libqtgui4
yes | sudo apt insall libqtwebkit-dev
yes | sudo apt insall libqtwebkit4
yes | sudo apt insall libquadmath0
yes | sudo apt insall librados2
yes | sudo apt insall libraptor2-0
yes | sudo apt insall librarian0
yes | sudo apt insall librasqal3
yes | sudo apt insall libraw1394-11
yes | sudo apt insall librbd1
yes | sudo apt insall librdf0
yes | sudo apt insall libreadline-dev
yes | sudo apt insall libreadline6
yes | sudo apt insall libreadline6-dev
yes | sudo apt insall libregexp-assemble-perl
yes | sudo apt insall libregexp-common-perl
yes | sudo apt insall libreoffice-base
yes | sudo apt insall libreoffice-calc
yes | sudo apt insall libreoffice-common
yes | sudo apt insall libreoffice-core
yes | sudo apt insall libreoffice-draw
yes | sudo apt insall libreoffice-impress
yes | sudo apt insall libreoffice-math
yes | sudo apt insall libreoffice-writer
yes | sudo apt insall libresid-builder0c2a
yes | sudo apt insall librest-0.7-0
yes | sudo apt insall librevenge-0.0-0
yes | sudo apt insall librsvg2-2
yes | sudo apt insall librsvg2-common
yes | sudo apt insall librtmp1
yes | sudo apt insall libsamplerate0
yes | sudo apt insall libsane
yes | sudo apt insall libsane-common
yes | sudo apt insall libsane-extras
yes | sudo apt insall libsane-extras-common
yes | sudo apt insall libsane-hpaio
yes | sudo apt insall libsasl2-2
yes | sudo apt insall libsasl2-modules
yes | sudo apt insall libsasl2-modules-db
yes | sudo apt insall libschroedinger-1.0-0
yes | sudo apt insall libsctp1
yes | sudo apt insall libsdl-image1.2
yes | sudo apt insall libsdl1.2debian
yes | sudo apt insall libseccomp2
yes | sudo apt insall libsecret-1-0
yes | sudo apt insall libsecret-common
yes | sudo apt insall libselinux1
yes | sudo apt insall libsemanage-common
yes | sudo apt insall libsemanage1
yes | sudo apt insall libsensors4
yes | sudo apt insall libsepol1
yes | sudo apt insall libservlet2.5-java
yes | sudo apt insall libsgutils2-2
yes | sudo apt insall libshine3
yes | sudo apt insall libshout3
yes | sudo apt insall libsidplay2
yes | sudo apt insall libsigc++-2.0-0c2a
yes | sudo apt insall libsigsegv2
yes | sudo apt insall libslang2
yes | sudo apt insall libsm6
yes | sudo apt insall libsmartcols1
yes | sudo apt insall libsmbclient
yes | sudo apt insall libsndfile1
yes | sudo apt insall libsnmp-base
yes | sudo apt insall libsnmp30
yes | sudo apt insall libsoftware-license-perl
yes | sudo apt insall libsolid4
yes | sudo apt insall libsonic0
yes | sudo apt insall libsoprano4
yes | sudo apt insall libsoup-gnome2.4-1
yes | sudo apt insall libsoup2.4-1
yes | sudo apt insall libspectre1
yes | sudo apt insall libspeechd2
yes | sudo apt insall libspeex1
yes | sudo apt insall libspeexdsp1
yes | sudo apt insall libspice-server1
yes | sudo apt insall libsqlite3-0
yes | sudo apt insall libss2
yes | sudo apt insall libssh-gcrypt-4
yes | sudo apt insall libssh2-1
yes | sudo apt insall libssl1.0.0
yes | sudo apt insall libstartup-notification0
yes | sudo apt insall libstdc++-4.9-dev
yes | sudo apt insall libstdc++6
yes | sudo apt insall libstreamanalyzer0
yes | sudo apt insall libstreams0
yes | sudo apt insall libsub-exporter-perl
yes | sudo apt insall libsub-install-perl
yes | sudo apt insall libsub-name-perl
yes | sudo apt insall libswitch-perl
yes | sudo apt insall libswscale3
yes | sudo apt insall libsysfs2
yes | sudo apt insall libsystemd0
yes | sudo apt insall libtag1-vanilla
yes | sudo apt insall libtag1c2a
yes | sudo apt insall libtalloc2
yes | sudo apt insall libtasn1-6
yes | sudo apt insall libtcl8.6
yes | sudo apt insall libtdb1
yes | sudo apt insall libteamdctl0
yes | sudo apt insall libterm-ui-perl
yes | sudo apt insall libtevent0
yes | sudo apt insall libtext-charwidth-perl
yes | sudo apt insall libtext-iconv-perl
yes | sudo apt insall libtext-soundex-perl
yes | sudo apt insall libtext-template-perl
yes | sudo apt insall libtext-unidecode-perl
yes | sudo apt insall libtext-wrapi18n-perl
yes | sudo apt insall libthai-data
yes | sudo apt insall libthai0
yes | sudo apt insall libtheora0
yes | sudo apt insall libthreadweaver4
yes | sudo apt insall libtie-ixhash-perl
yes | sudo apt insall libtiff5
yes | sudo apt insall libtimedate-perl
yes | sudo apt insall libtinfo-dev
yes | sudo apt insall libtinfo5
yes | sudo apt insall libtinyxml2.6.2
yes | sudo apt insall libtirpc1
yes | sudo apt insall libtk8.6
yes | sudo apt insall libtokyocabinet9
yes | sudo apt insall libtool
yes | sudo apt insall libtool-bin
yes | sudo apt insall libtwolame0
yes | sudo apt insall libtxc-dxtn-s2tc0
yes | sudo apt insall libubsan0
yes | sudo apt insall libudev1
yes | sudo apt insall libudisks2-0
yes | sudo apt insall libumfpack5.6.2
yes | sudo apt insall libunique-1.0-0
yes | sudo apt insall libupnp6
yes | sudo apt insall libupower-glib3
yes | sudo apt insall liburi-perl
yes | sudo apt insall libusageenvironment1
yes | sudo apt insall libusb-0.1-4
yes | sudo apt insall libusb-1.0-0
yes | sudo apt insall libusbmuxd2
yes | sudo apt insall libusbredirparser1
yes | sudo apt insall libustr-1.0-1
yes | sudo apt insall libutempter0
yes | sudo apt insall libuuid-perl
yes | sudo apt insall libuuid1
yes | sudo apt insall libv4l-0
yes | sudo apt insall libv4lconvert0
yes | sudo apt insall libva-drm1
yes | sudo apt insall libva-x11-1
yes | sudo apt insall libva1
yes | sudo apt insall libvcdinfo0
yes | sudo apt insall libvdeplug2
yes | sudo apt insall libvdpau1
yes | sudo apt insall libvisio-0.1-1
yes | sudo apt insall libvisual-0.4-0
yes | sudo apt insall libvisual-0.4-plugins
yes | sudo apt insall libvlc5
yes | sudo apt insall libvlccore8
yes | sudo apt insall libvncclient0
yes | sudo apt insall libvorbis0a
yes | sudo apt insall libvorbisenc2
yes | sudo apt insall libvorbisfile3
yes | sudo apt insall libvpx1
yes | sudo apt insall libvte-2.90-9
yes | sudo apt insall libvte-2.90-common
yes | sudo apt insall libvte-common
yes | sudo apt insall libvte9
yes | sudo apt insall libwavpack1
yes | sudo apt insall libwayland-client0
yes | sudo apt insall libwayland-cursor0
yes | sudo apt insall libwayland-egl1-mesa
yes | sudo apt insall libwayland-server0
yes | sudo apt insall libwbclient0
yes | sudo apt insall libwebkitgtk-3.0-0
yes | sudo apt insall libwebkitgtk-3.0-common
yes | sudo apt insall libwebp5
yes | sudo apt insall libwebpdemux1
yes | sudo apt insall libwebpmux1
yes | sudo apt insall libwebrtc-audio-processing-0
yes | sudo apt insall libwinpr-crt0.1
yes | sudo apt insall libwinpr-crypto0.1
yes | sudo apt insall libwinpr-dsparse0.1
yes | sudo apt insall libwinpr-environment0.1
yes | sudo apt insall libwinpr-file0.1
yes | sudo apt insall libwinpr-handle0.1
yes | sudo apt insall libwinpr-heap0.1
yes | sudo apt insall libwinpr-input0.1
yes | sudo apt insall libwinpr-interlocked0.1
yes | sudo apt insall libwinpr-library0.1
yes | sudo apt insall libwinpr-path0.1
yes | sudo apt insall libwinpr-pool0.1
yes | sudo apt insall libwinpr-registry0.1
yes | sudo apt insall libwinpr-rpc0.1
yes | sudo apt insall libwinpr-sspi0.1
yes | sudo apt insall libwinpr-synch0.1
yes | sudo apt insall libwinpr-sysinfo0.1
yes | sudo apt insall libwinpr-thread0.1
yes | sudo apt insall libwinpr-utils0.1
yes | sudo apt insall libwmf0.2-7
yes | sudo apt insall libwnck-3-0
yes | sudo apt insall libwnck-3-common
yes | sudo apt insall libwnck-common
yes | sudo apt insall libwnck22
yes | sudo apt insall libwpd-0.10-10
yes | sudo apt insall libwpg-0.3-3
yes | sudo apt insall libwps-0.3-3
yes | sudo apt insall libwrap0
yes | sudo apt insall libwww-perl
yes | sudo apt insall libwww-robotrules-perl
yes | sudo apt insall libwxbase3.0-0
yes | sudo apt insall libwxgtk3.0-0
yes | sudo apt insall libx11-6
yes | sudo apt insall libx11-data
yes | sudo apt insall libx11-dev
yes | sudo apt insall libx11-doc
yes | sudo apt insall libx11-protocol-perl
yes | sudo apt insall libx11-xcb-dev
yes | sudo apt insall libx11-xcb1
yes | sudo apt insall libx264-142
yes | sudo apt insall libxapian22
yes | sudo apt insall libxatracker2
yes | sudo apt insall libxau-dev
yes | sudo apt insall libxau6
yes | sudo apt insall libxaw7
yes | sudo apt insall libxcb-composite0
yes | sudo apt insall libxcb-dri2-0
yes | sudo apt insall libxcb-dri2-0-dev
yes | sudo apt insall libxcb-dri3-0
yes | sudo apt insall libxcb-dri3-dev
yes | sudo apt insall libxcb-glx0
yes | sudo apt insall libxcb-glx0-dev
yes | sudo apt insall libxcb-keysyms1
yes | sudo apt insall libxcb-present-dev
yes | sudo apt insall libxcb-present0
yes | sudo apt insall libxcb-randr0
yes | sudo apt insall libxcb-randr0-dev
yes | sudo apt insall libxcb-render0
yes | sudo apt insall libxcb-render0-dev
yes | sudo apt insall libxcb-shape0
yes | sudo apt insall libxcb-shape0-dev
yes | sudo apt insall libxcb-shm0
yes | sudo apt insall libxcb-sync-dev
yes | sudo apt insall libxcb-sync1
yes | sudo apt insall libxcb-util0
yes | sudo apt insall libxcb-xfixes0
yes | sudo apt insall libxcb-xfixes0-dev
yes | sudo apt insall libxcb-xv0
yes | sudo apt insall libxcb1
yes | sudo apt insall libxcb1-dev
yes | sudo apt insall libxcomposite1
yes | sudo apt insall libxcursor1
yes | sudo apt insall libxdamage-dev
yes | sudo apt insall libxdamage1
yes | sudo apt insall libxdmcp-dev
yes | sudo apt insall libxdmcp6
yes | sudo apt insall libxen-4.4
yes | sudo apt insall libxenstore3.0
yes | sudo apt insall libxext-dev
yes | sudo apt insall libxext6
yes | sudo apt insall libxfixes-dev
yes | sudo apt insall libxfixes3
yes | sudo apt insall libxfont1
yes | sudo apt insall libxft2
yes | sudo apt insall libxi6
yes | sudo apt insall libxinerama1
yes | sudo apt insall libxkbcommon0
yes | sudo apt insall libxkbfile1
yes | sudo apt insall libxklavier16
yes | sudo apt insall libxml-libxml-perl
yes | sudo apt insall libxml-namespacesupport-perl
yes | sudo apt insall libxml-parser-perl
yes | sudo apt insall libxml-sax-base-perl
yes | sudo apt insall libxml-sax-expat-perl
yes | sudo apt insall libxml-sax-perl
yes | sudo apt insall libxml-twig-perl
yes | sudo apt insall libxml-xpathengine-perl
yes | sudo apt insall libxml2
yes | sudo apt insall libxml2-utils
yes | sudo apt insall libxmu6
yes | sudo apt insall libxmuu1
yes | sudo apt insall libxpm4
yes | sudo apt insall libxrandr2
yes | sudo apt insall libxrender1
yes | sudo apt insall libxres1
yes | sudo apt insall libxshmfence-dev
yes | sudo apt insall libxshmfence1
yes | sudo apt insall libxslt1.1
yes | sudo apt insall libxss1
yes | sudo apt insall libxt6
yes | sudo apt insall libxtables10
yes | sudo apt insall libxtst6
yes | sudo apt insall libxv1
yes | sudo apt insall libxvidcore4
yes | sudo apt insall libxvmc1
yes | sudo apt insall libxxf86dga1
yes | sudo apt insall libxxf86vm-dev
yes | sudo apt insall libxxf86vm1
yes | sudo apt insall libyajl2
yes | sudo apt insall libzvbi-common
yes | sudo apt insall libzvbi0
yes | sudo apt insall lightdm
yes | sudo apt insall lightdm-gtk-greeter
yes | sudo apt insall linux-base
yes | sudo apt insall linux-compiler-gcc-4.8-x86
yes | sudo apt insall linux-headers-3.16.0-4-586
yes | sudo apt insall linux-headers-3.16.0-4-686-pae
yes | sudo apt insall linux-headers-3.16.0-4-common
yes | sudo apt insall linux-image-3.16.0-4-586
yes | sudo apt insall linux-image-3.16.0-4-686-pae
yes | sudo apt insall linux-image-586
yes | sudo apt insall linux-kbuild-3.16
yes | sudo apt insall linux-libc-dev
yes | sudo apt insall lksctp-tools
yes | sudo apt insall locales
yes | sudo apt insall login
yes | sudo apt insall logrotate
yes | sudo apt insall lsb-base
yes | sudo apt insall lsb-release
yes | sudo apt insall lsof
yes | sudo apt insall m4
yes | sudo apt insall make
yes | sudo apt insall man-db
yes | sudo apt insall manpages
yes | sudo apt insall manpages-dev
yes | sudo apt insall marco
yes | sudo apt insall marco-common
yes | sudo apt insall mate-applets
yes | sudo apt insall mate-applets-common
yes | sudo apt insall mate-backgrounds
yes | sudo apt insall mate-control-center
yes | sudo apt insall mate-control-center-common
yes | sudo apt insall mate-desktop
yes | sudo apt insall mate-desktop-common
yes | sudo apt insall mate-desktop-environment
yes | sudo apt insall mate-desktop-environment-core
yes | sudo apt insall mate-icon-theme
yes | sudo apt insall mate-icon-theme-faenza
yes | sudo apt insall mate-media
yes | sudo apt insall mate-media-common
yes | sudo apt insall mate-media-pulse
yes | sudo apt insall mate-menus
yes | sudo apt insall mate-notification-daemon
yes | sudo apt insall mate-panel
yes | sudo apt insall mate-panel-common
yes | sudo apt insall mate-polkit
yes | sudo apt insall mate-polkit-common
yes | sudo apt insall mate-power-manager
yes | sudo apt insall mate-power-manager-common
yes | sudo apt insall mate-screensaver
yes | sudo apt insall mate-screensaver-common
yes | sudo apt insall mate-session-manager
yes | sudo apt insall mate-settings-daemon
yes | sudo apt insall mate-settings-daemon-common
yes | sudo apt insall mate-settings-daemon-pulse
yes | sudo apt insall mate-system-monitor
yes | sudo apt insall mate-system-monitor-common
yes | sudo apt insall mate-terminal
yes | sudo apt insall mate-terminal-common
yes | sudo apt insall mate-themes
yes | sudo apt insall mate-utils
yes | sudo apt insall mate-utils-common
yes | sudo apt insall mawk
yes | sudo apt insall menu
yes | sudo apt insall menu-xdg
yes | sudo apt insall mercurial
yes | sudo apt insall mercurial-common
yes | sudo apt insall mesa-common-dev
yes | sudo apt insall mime-support
yes | sudo apt insall mlocate
yes | sudo apt insall mobile-broadband-provider-info
yes | sudo apt insall modemmanager
yes | sudo apt insall mount
yes | sudo apt insall mscompress
yes | sudo apt insall multiarch-support
yes | sudo apt insall murrine-themes
yes | sudo apt insall mutt
yes | sudo apt insall mysql-common
yes | sudo apt insall mythes-en-us
yes | sudo apt insall nano
yes | sudo apt insall ncurses-base
yes | sudo apt insall ncurses-bin
yes | sudo apt insall ncurses-term
yes | sudo apt insall nepomuk-core-data
yes | sudo apt insall net-tools
yes | sudo apt insall netbase
yes | sudo apt insall netcat
yes | sudo apt insall netcat-traditional
yes | sudo apt insall netselect
yes | sudo apt insall netselect-apt
yes | sudo apt insall network-manager
yes | sudo apt insall network-manager-gnome
yes | sudo apt insall nfacct
yes | sudo apt insall nfs-common
yes | sudo apt insall nginx
yes | sudo apt insall nginx-common
yes | sudo apt insall nginx-full
yes | sudo apt insall notification-daemon
yes | sudo apt insall ntfs-3g
yes | sudo apt insall ntrack-module-libnl-0
yes | sudo apt insall openbios-ppc
yes | sudo apt insall openbios-sparc
yes | sudo apt insall openhackware
yes | sudo apt insall openjdk-7-jre
yes | sudo apt insall openjdk-7-jre-headless
yes | sudo apt insall openprinting-ppds
yes | sudo apt insall openssh-client
yes | sudo apt insall openssl
yes | sudo apt insall oracle-java8-installer
yes | sudo apt insall oracle-java8-set-default
yes | sudo apt insall os-prober
yes | sudo apt insall oxygen-icon-theme
yes | sudo apt insall p11-kit
yes | sudo apt insall p11-kit-modules
yes | sudo apt insall p7zip-full
yes | sudo apt insall parted
yes | sudo apt insall passwd
yes | sudo apt insall patch
yes | sudo apt insall pciutils
yes | sudo apt insall perl
yes | sudo apt insall perl-base
yes | sudo apt insall perl-modules
yes | sudo apt insall phonon
yes | sudo apt insall phonon-backend-vlc
yes | sudo apt insall pinentry-gtk2
yes | sudo apt insall plasma-scriptengine-javascript
yes | sudo apt insall pluma
yes | sudo apt insall pluma-common
yes | sudo apt insall policykit-1
yes | sudo apt insall policykit-1-gnome
yes | sudo apt insall poppler-data
yes | sudo apt insall poppler-utils
yes | sudo apt insall popularity-contest
yes | sudo apt insall powermgmt-base
yes | sudo apt insall ppp
yes | sudo apt insall printer-driver-all
yes | sudo apt insall printer-driver-brlaser
yes | sudo apt insall printer-driver-c2050
yes | sudo apt insall printer-driver-c2esp
yes | sudo apt insall printer-driver-cjet
yes | sudo apt insall printer-driver-dymo
yes | sudo apt insall printer-driver-escpr
yes | sudo apt insall printer-driver-foo2zjs
yes | sudo apt insall printer-driver-foo2zjs-common
yes | sudo apt insall printer-driver-gutenprint
yes | sudo apt insall printer-driver-hpcups
yes | sudo apt insall printer-driver-hpijs
yes | sudo apt insall printer-driver-m2300w
yes | sudo apt insall printer-driver-min12xxw
yes | sudo apt insall printer-driver-pnm2ppa
yes | sudo apt insall printer-driver-postscript-hp
yes | sudo apt insall printer-driver-ptouch
yes | sudo apt insall printer-driver-pxljr
yes | sudo apt insall printer-driver-sag-gdi
yes | sudo apt insall printer-driver-splix
yes | sudo apt insall procmail
yes | sudo apt insall procps
yes | sudo apt insall psmisc
yes | sudo apt insall pulseaudio
yes | sudo apt insall pulseaudio-module-x11
yes | sudo apt insall pulseaudio-utils
yes | sudo apt insall python
yes | sudo apt insall python-apt
yes | sudo apt insall python-apt-common
yes | sudo apt insall python-cairo
yes | sudo apt insall python-chardet
yes | sudo apt insall python-dbus
yes | sudo apt insall python-dbus-dev
yes | sudo apt insall python-debian
yes | sudo apt insall python-debianbts
yes | sudo apt insall python-defusedxml
yes | sudo apt insall python-docutils
yes | sudo apt insall python-gi
yes | sudo apt insall python-gobject
yes | sudo apt insall python-gobject-2
yes | sudo apt insall python-gst0.10
yes | sudo apt insall python-gtk2
yes | sudo apt insall python-imaging
yes | sudo apt insall python-iniparse
yes | sudo apt insall python-libxml2
yes | sudo apt insall python-minimal
yes | sudo apt insall python-notify
yes | sudo apt insall python-numpy
yes | sudo apt insall python-pexpect
yes | sudo apt insall python-pil
yes | sudo apt insall python-pkg-resources
yes | sudo apt insall python-pygments
yes | sudo apt insall python-qscintilla2
yes | sudo apt insall python-qt4
yes | sudo apt insall python-renderpm
yes | sudo apt insall python-reportbug
yes | sudo apt insall python-reportlab
yes | sudo apt insall python-reportlab-accel
yes | sudo apt insall python-roman
yes | sudo apt insall python-sip
yes | sudo apt insall python-six
yes | sudo apt insall python-soappy
yes | sudo apt insall python-support
yes | sudo apt insall python-talloc
yes | sudo apt insall python-wstools
yes | sudo apt insall python2.7
yes | sudo apt insall python2.7-minimal
yes | sudo apt insall python3
yes | sudo apt insall python3-brlapi
yes | sudo apt insall python3-cairo
yes | sudo apt insall python3-gi
yes | sudo apt insall python3-louis
yes | sudo apt insall python3-minimal
yes | sudo apt insall python3-pyatspi
yes | sudo apt insall python3-speechd
yes | sudo apt insall python3-xdg
yes | sudo apt insall python3.4
yes | sudo apt insall python3.4-minimal
yes | sudo apt insall qdbus
yes | sudo apt insall qemu
yes | sudo apt insall qemu-slof
yes | sudo apt insall qemu-system
yes | sudo apt insall qemu-system-arm
yes | sudo apt insall qemu-system-common
yes | sudo apt insall qemu-system-mips
yes | sudo apt insall qemu-system-misc
yes | sudo apt insall qemu-system-ppc
yes | sudo apt insall qemu-system-sparc
yes | sudo apt insall qemu-system-x86
yes | sudo apt insall qemu-user
yes | sudo apt insall qemu-user-static
yes | sudo apt insall qemu-utils
yes | sudo apt insall qpdf
yes | sudo apt insall qt-at-spi
yes | sudo apt insall qt4-designer
yes | sudo apt insall qt4-dev-tools
yes | sudo apt insall qt4-doc
yes | sudo apt insall qt4-linguist-tools
yes | sudo apt insall qt4-qmake
yes | sudo apt insall qtchooser
yes | sudo apt insall qtcore4-l10n
yes | sudo apt insall rarian-compat
yes | sudo apt insall readline-common
yes | sudo apt insall rename
yes | sudo apt insall reportbug
yes | sudo apt insall rpcbind
yes | sudo apt insall rsync
yes | sudo apt insall rsyslog
yes | sudo apt insall rtkit
yes | sudo apt insall samba-libs
yes | sudo apt insall sane-utils
yes | sudo apt insall seabios
yes | sudo apt insall sed
yes | sudo apt insall sensible-utils
yes | sudo apt insall sgml-base
yes | sudo apt insall sgml-data
yes | sudo apt insall shared-mime-info
yes | sudo apt insall sharutils
yes | sudo apt insall soprano-daemon
yes | sudo apt insall sound-theme-freedesktop
yes | sudo apt insall speech-dispatcher
yes | sudo apt insall speech-dispatcher-audio-plugins
yes | sudo apt insall sshfs
yes | sudo apt insall ssl-cert
yes | sudo apt insall startpar
yes | sudo apt insall sudo
yes | sudo apt insall synaptic
yes | sudo apt insall systemd
yes | sudo apt insall systemd-sysv
yes | sudo apt insall sysv-rc
yes | sudo apt insall sysvinit-utils
yes | sudo apt insall tar
yes | sudo apt insall task-desktop
yes | sudo apt insall task-english
yes | sudo apt insall task-mate-desktop
yes | sudo apt insall task-print-server
yes | sudo apt insall tasksel
yes | sudo apt insall tasksel-data
yes | sudo apt insall tcl
yes | sudo apt insall tcl8.6
yes | sudo apt insall tcpd
yes | sudo apt insall telnet
yes | sudo apt insall testdisk
yes | sudo apt insall texinfo
yes | sudo apt insall time
yes | sudo apt insall tk
yes | sudo apt insall tk8.6
yes | sudo apt insall tortoisehg
yes | sudo apt insall traceroute
yes | sudo apt insall tzdata
yes | sudo apt insall tzdata-java
yes | sudo apt insall ucf
yes | sudo apt insall udev
yes | sudo apt insall udisks
yes | sudo apt insall udisks2
yes | sudo apt insall unar
yes | sudo apt insall uno-libs3
yes | sudo apt insall unrar-free
yes | sudo apt insall unzip
yes | sudo apt insall update-inetd
yes | sudo apt insall upower
yes | sudo apt insall usb-modeswitch
yes | sudo apt insall usb-modeswitch-data
yes | sudo apt insall usbmuxd
yes | sudo apt insall usbutils
yes | sudo apt insall util-linux
yes | sudo apt insall util-linux-locales
yes | sudo apt insall va-driver-all
yes | sudo apt insall vdpau-va-driver
yes | sudo apt insall vim-common
yes | sudo apt insall vim-tiny
yes | sudo apt insall vlc
yes | sudo apt insall vlc-data
yes | sudo apt insall vlc-nox
yes | sudo apt insall vlc-plugin-notify
yes | sudo apt insall vlc-plugin-pulse
yes | sudo apt insall vlc-plugin-samba
yes | sudo apt insall vsftpd
yes | sudo apt insall w3m
yes | sudo apt insall wamerican
yes | sudo apt insall wget
yes | sudo apt insall whiptail
yes | sudo apt insall whois
yes | sudo apt insall wireless-regdb
yes | sudo apt insall wpasupplicant
yes | sudo apt insall x11-apps
yes | sudo apt insall x11-common
yes | sudo apt insall x11-session-utils
yes | sudo apt insall x11-utils
yes | sudo apt insall x11-xkb-utils
yes | sudo apt insall x11-xserver-utils
yes | sudo apt insall x11proto-core-dev
yes | sudo apt insall x11proto-damage-dev
yes | sudo apt insall x11proto-dri2-dev
yes | sudo apt insall x11proto-fixes-dev
yes | sudo apt insall x11proto-gl-dev
yes | sudo apt insall x11proto-input-dev
yes | sudo apt insall x11proto-kb-dev
yes | sudo apt insall x11proto-xext-dev
yes | sudo apt insall x11proto-xf86vidmode-dev
yes | sudo apt insall xauth
yes | sudo apt insall xbitmaps
yes | sudo apt insall xbrlapi
yes | sudo apt insall xdg-user-dirs
yes | sudo apt insall xdg-utils
yes | sudo apt insall xfonts-100dpi
yes | sudo apt insall xfonts-75dpi
yes | sudo apt insall xfonts-base
yes | sudo apt insall xfonts-encodings
yes | sudo apt insall xfonts-scalable
yes | sudo apt insall xfonts-utils
yes | sudo apt insall xinit
yes | sudo apt insall xkb-data
yes | sudo apt insall xml-core
yes | sudo apt insall xorg
yes | sudo apt insall xorg-docs-core
yes | sudo apt insall xorg-sgml-doctools
yes | sudo apt insall xserver-common
yes | sudo apt insall xserver-xorg
yes | sudo apt insall xserver-xorg-core
yes | sudo apt insall xserver-xorg-input-all
yes | sudo apt insall xserver-xorg-input-evdev
yes | sudo apt insall xserver-xorg-input-mouse
yes | sudo apt insall xserver-xorg-input-synaptics
yes | sudo apt insall xserver-xorg-input-vmmouse
yes | sudo apt insall xserver-xorg-input-wacom
yes | sudo apt insall xserver-xorg-video-all
yes | sudo apt insall xserver-xorg-video-ati
yes | sudo apt insall xserver-xorg-video-cirrus
yes | sudo apt insall xserver-xorg-video-fbdev
yes | sudo apt insall xserver-xorg-video-geode
yes | sudo apt insall xserver-xorg-video-intel
yes | sudo apt insall xserver-xorg-video-mach64
yes | sudo apt insall xserver-xorg-video-mga
yes | sudo apt insall xserver-xorg-video-modesetting
yes | sudo apt insall xserver-xorg-video-neomagic
yes | sudo apt insall xserver-xorg-video-nouveau
yes | sudo apt insall xserver-xorg-video-openchrome
yes | sudo apt insall xserver-xorg-video-qxl
yes | sudo apt insall xserver-xorg-video-r128
yes | sudo apt insall xserver-xorg-video-radeon
yes | sudo apt insall xserver-xorg-video-savage
yes | sudo apt insall xserver-xorg-video-siliconmotion
yes | sudo apt insall xserver-xorg-video-sisusb
yes | sudo apt insall xserver-xorg-video-tdfx
yes | sudo apt insall xserver-xorg-video-trident
yes | sudo apt insall xserver-xorg-video-vesa
yes | sudo apt insall xserver-xorg-video-vmware
yes | sudo apt insall xsltproc
yes | sudo apt insall xterm
yes | sudo apt insall xtrans-dev
yes | sudo apt insall xz-utils
yes | sudo apt insall zenity
yes | sudo apt insall zenity-common
yes | sudo apt insall zip
yes | sudo apt insall zlib1g